#!/bin/sh

./add-c-extern.sh support.h
./add-c-extern.sh interface.h

# Don't put the test too early (before gtk.h is loaded):
# need to put the test after support.h

sed -e s'/#include .support.h./#include "support.h"\
\
#if (GTK_MAJOR_VERSION == 1) || defined (GTK_ENABLE_BROKEN)/' interface.c > tmp-interface.c
echo "#endif" >>  tmp-interface.c
mv tmp-interface.c interface.c

sed -e s'/#include .support.h./#include "support.h"\
\
#if (GTK_MAJOR_VERSION == 1) || defined (GTK_ENABLE_BROKEN)\n#else/' gtk2-interface.c > tmp-interface.c

# on reflection, try not to mess with gtk2-interface.c
#
# only add an endif if there wasn't one there already:
# If it is not there grep give status code 1.
# grep endif gtk2-interface.c > /dev/null
# grepstatus=$?
# if [ $grepstatus = 1 ] ; then
#    echo "#endif" >>  tmp-interface.c
# fi
# mv tmp-interface.c gtk2-interface.c


sh fix-gettext.sh support.h
if test -e main.c ; then 
	rm main.c
fi

