/*
 * coot-utils/assembly-interface.hh
 *
 * Copyright 2026 by Medical Research Council
 * Author: Paul Emsley
 *
 * This file is part of Coot
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copies of the GNU General Public License and
 * the GNU Lesser General Public License along with this program; if not,
 * write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA, 02110-1301, USA.
 * See http://www.gnu.org/licenses/
 *
 */

#ifndef ASSEMBLY_INTERFACE_HH
#define ASSEMBLY_INTERFACE_HH

#include <string>
#include <vector>
#include <map>
#include <tuple>

#include <mmdb2/mmdb_manager.h>
#include <clipper/core/coords.h>

namespace coot {

   // Atomic solvation parameter (ASP) atom types from Krissinel & Henrick (2007)
   // Eisenberg & McLachlan classification
   enum class asp_atom_type_t { C, S, O_N, N_PLUS, O_MINUS };

   // ASP values in cal/(mol * A^2), from Table 1 of Krissinel & Henrick (2007)
   // Column A (Eisenberg & McLachlan values)
   double asp_value(asp_atom_type_t type);

   // Classify an atom into ASP type based on element and environment
   asp_atom_type_t classify_asp_atom_type(mmdb::Atom *atom_p);

   // Van der Waals radii for ASA calculation (in Angstroms)
   double vdw_radius(const std::string &element);

   // Identifies a monomeric unit: a chain in a particular symmetry context
   struct monomer_id_t {
      std::string chain_id;
      int symop_no;         // symmetry operator index (0 = identity)
      int x_shift, y_shift, z_shift;  // unit cell translation
      monomer_id_t() : symop_no(0), x_shift(0), y_shift(0), z_shift(0) {}
      monomer_id_t(const std::string &cid, int s, int x, int y, int z)
         : chain_id(cid), symop_no(s), x_shift(x), y_shift(y), z_shift(z) {}
      bool operator==(const monomer_id_t &o) const {
         return chain_id == o.chain_id && symop_no == o.symop_no &&
                x_shift == o.x_shift && y_shift == o.y_shift && z_shift == o.z_shift;
      }
      bool operator<(const monomer_id_t &o) const;
      bool is_asu() const { return symop_no == 0 && x_shift == 0 && y_shift == 0 && z_shift == 0; }
      std::string label() const;
   };

   // A chain of atoms generated by a symmetry operation
   struct symmetry_chain_t {
      monomer_id_t id;
      std::vector<clipper::Coord_orth> positions;  // transformed atom positions
      std::vector<mmdb::Atom *> source_atoms;      // original atoms in ASU
      mmdb::mat44 transform;
   };

   // Per-interface data between two monomeric units
   struct assembly_interface_t {
      monomer_id_t monomer_1;
      monomer_id_t monomer_2;
      double buried_surface_area;      // total BSA in A^2
      std::map<asp_atom_type_t, double> buried_area_by_type;  // BSA per atom type
      int n_hydrogen_bonds;
      int n_salt_bridges;
      int n_disulfide_bonds;
      double delta_g_solv;   // solvation energy contribution (kcal/mol)
      double delta_g_cont;   // contact energy contribution (kcal/mol)
      double delta_g_int;    // total binding energy (kcal/mol), Eq. 9
      clipper::Coord_orth centre;      // geometric centre of interface
      int n_interface_atoms_1;         // atoms from monomer_1 at interface
      int n_interface_atoms_2;         // atoms from monomer_2 at interface
      int n_interface_residues_1;
      int n_interface_residues_2;
      assembly_interface_t() :
         buried_surface_area(0.0), n_hydrogen_bonds(0), n_salt_bridges(0),
         n_disulfide_bonds(0), delta_g_solv(0.0), delta_g_cont(0.0),
         delta_g_int(0.0), n_interface_atoms_1(0), n_interface_atoms_2(0),
         n_interface_residues_1(0), n_interface_residues_2(0) {}
   };

   // Properties of a monomeric unit needed for entropy calculation
   struct monomer_properties_t {
      monomer_id_t id;
      double mass;                // molecular mass in Da
      double surface_area;        // total ASA in A^2
      double J1, J2, J3;          // principal moments of inertia
      int symmetry_number;        // gamma - number of unique rotations superposing onto itself
      int n_atoms;
      int n_residues;
      monomer_properties_t() : mass(0.0), surface_area(0.0),
         J1(0.0), J2(0.0), J3(0.0), symmetry_number(1),
         n_atoms(0), n_residues(0) {}
   };

   // Shrake-Rupley accessible surface area calculation
   // Returns per-atom ASA values in A^2
   // probe_radius: water probe radius (default 1.4 A)
   // n_sphere_points: number of test points on sphere (default 960)
   std::vector<double> shrake_rupley_asa(const std::vector<clipper::Coord_orth> &positions,
                                         const std::vector<double> &radii,
                                         double probe_radius = 1.4,
                                         int n_sphere_points = 960);

   // Generate uniformly distributed points on a unit sphere (Fibonacci lattice)
   std::vector<clipper::Coord_orth> fibonacci_sphere_points(int n_points);

   // Calculate molecular mass from atoms
   double molecular_mass(mmdb::Manager *mol_p, int selHnd);

   // Calculate principal moments of inertia
   // Returns (J1, J2, J3) sorted ascending
   std::tuple<double, double, double> principal_moments_of_inertia(
      const std::vector<clipper::Coord_orth> &positions,
      const std::vector<double> &masses);

   // Main class for finding macromolecular assemblies
   class assembly_detector_t {

      mmdb::Manager *mol_p;
      double contact_dist;    // max distance for interface contact (default 4.5 A)

      // Generated symmetry chains
      std::vector<symmetry_chain_t> symmetry_chains;

      // Detected interfaces
      std::vector<assembly_interface_t> interfaces;

      // Monomer properties (for entropy calculation)
      std::map<monomer_id_t, monomer_properties_t> monomer_props;

      // Internal methods
      void generate_symmetry_chains();
      void find_interfaces();
      void calculate_interface_bsa(assembly_interface_t *iface_p,
                                   const symmetry_chain_t &chain_1,
                                   const symmetry_chain_t &chain_2);
      void count_interface_contacts(assembly_interface_t *iface_p,
                                    const symmetry_chain_t &chain_1,
                                    const symmetry_chain_t &chain_2);
      void calculate_interface_energetics(assembly_interface_t *iface_p);
      void calculate_monomer_properties();

   public:

      // Construct from an mmdb::Manager with crystal symmetry information.
      // contact_dist: maximum atom-atom distance to consider as an interface contact
      assembly_detector_t(mmdb::Manager *mol_in, double contact_dist_in = 4.5);

      // Run the full interface detection
      void detect_interfaces();

      // Access results
      const std::vector<assembly_interface_t> &get_interfaces() const { return interfaces; }
      const std::map<monomer_id_t, monomer_properties_t> &get_monomer_properties() const {
         return monomer_props;
      }

      // Summary output
      std::string interfaces_summary() const;
   };

} // namespace coot

#endif // ASSEMBLY_INTERFACE_HH
