
# to find clipper.pc, you will need to do something like
# export PKG_CONFIG_PATH=$COOT_DIR/lib/pkgconfig

COOT_DIR=$(HOME)/freshcoot/experimental_systemlibsbuild/prefix2

CXXFLAGS= \
   -I$(COOT_DIR)/include \
   -I$(COOT_DIR)/include/coot \
   -I/usr/include/rdkit \
   -I/usr/include/eigen3 \
   -DUSE_LIBCURL \
   -DVERSION="\"dummyVERSION\"" \
   `pkg-config --cflags gtk4` \
   -ggdb -O2 -march=native -std=c++20
# `pkg-config --cflags epoxy` 
# `pkg-config --cflags clipper` 

LDLIBS=-fuse-ld=mold \
       -L$(COOT_DIR)/lib \
       `pkg-config --libs gtk4`  \
        -g \
        -Wl,--export-dynamic,--rpath=$(COOT_DIR)/lib \
        -lfreetype -lm -ldl -lpthread -lpng \
        -lcoot-geometry -lcoot-lidia-core -lcoot-utils \
        -lRDKitDepictor -lRDKitMolTransforms -lRDKitSmilesParse -lRDKitMolDraw2D -lRDKitGraphMol -lRDKitRDInchiLib  -lRDKitRDGeneral -lRDKitRDGeometryLib -lRDKitFileParsers -lRDKitDescriptors -lRDKitChemTransforms -lRDKitSubstructMatch -lRDKitGenericGroups -lRDKitDataStructs -lRDKitFMCS \
        -lcoordgen \
        -lboost_iostreams -lboost_serialization -lcurl

	   # -lcoot-ligand -lcoot-ideal -lcoot-coords -lcoot-map-utils -lcoot-coord-utils -lcoot-geometry -lmmdb2 
       #`pkg-config --libs epoxy` 
       #`pkg-config --libs clipper` 

HEADERS = \
    state.hpp \
    ui.hpp \
    utils.hpp \
    notifier.hpp \
    generators.hpp \
    inchi_key_database.hpp \
    ligand_editor_canvas/model.hpp \
    ligand_editor_canvas/core.hpp \
    ligand_editor_canvas/tools.hpp \
    ligand_editor_canvas/render.hpp \
    ligand_editor_canvas.hpp \
    layla_embedded.hpp \
    network_utils.hpp \
    similar_ligands.hpp \
    qed.hpp

SOURCES = \
    state.cpp \
    signals.cpp \
    ui.cpp \
    utils.cpp \
    notifier.cpp \
    generators.cpp \
    inchi_key_database.cpp \
    ligand_editor_canvas/model.cpp \
    ligand_editor_canvas/core.cpp \
    ligand_editor_canvas/tools.cpp \
    ligand_editor_canvas/render.cpp \
    ligand_editor_canvas.cpp \
    layla_embedded.cpp \
    network_utils.cpp \
    similar_ligands.cpp \
    qed.cpp \
    main.cpp



OBJS := $(patsubst %.cpp,%.o,$(SOURCES))

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

layla: $(OBJS) $(HEADERS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDLIBS)
