
CLIPPER_CXXFLAGS = -I/Users/paulemsley/ccp4/ysbl-distro-based/include

CLIPPER_LIBS = -L/Users/paulemsley/ccp4/ysbl-distro-based/lib -lclipper-ccp4 \
	-lclipper-cif -lclipper-phs -lclipper-contrib -lclipper-mmdb \
	-lclipper-core -lccp4c -L/Users/paulemsley/ccp4/ysbl-distro-based/lib \
	-L/Users/paulemsley/ccp4/ysbl-distro-based -lmmdb -lm -lrfftw -lfftw -lz -lm

INCLUDES = $(CLIPPER_CXXFLAGS)
LDLIBS = $(CLIPPER_LIBS)

rama-data: rama-data.cc
	$(CXX) $(INCLUDES) -o $@ $(LDLIBS) $^

rama-doughnut: rama-doughnut.cc
	$(CXX) $(INCLUDES) -o $@ $(LDLIBS) $^

