#!/bin/sh

./add-c-extern.sh support.h
./add-c-extern.sh interface.h

# Don't put the test too early (before gtk.h is loaded):
# need to put the test after support.h

# Francois says that in support.h, interface.c  we need to replace:
#
# #include <unistd.h>
#
# with
#
# #ifndef _MSC_VER
# #include <unistd.h>
# #endif

sed -e 's/#include .unistd.h./#ifndef _MSC_VER\n#include <unistd.h>\n#endif/' \
    interface.c > tmp-interface.c
mv tmp-interface.c interface.c

sed -e 's/#include <unistd.h>/#ifndef _MSC_VER\n#include <unistd.h>\n#else\n#define S_ISREG(m) (((m) \& S_IFMT) == S_IFREG)\n#endif/' \
    support.c > support-tmp.c
mv support-tmp.c support.c



# on reflection, try not to mess with gtk2-interface.c
#
# only add an endif if there wasn't one there already:
# If it is not there grep give status code 1.
# grep endif gtk2-interface.c > /dev/null
# grepstatus=$?
# if [ $grepstatus = 1 ] ; then
#    echo "#endif" >>  tmp-interface.c
# fi
# mv tmp-interface.c gtk2-interface.c


#jsh fix-gettext.sh support.h
#jif test -e main.c ; then 
#j	rm main.c
#jfi


# for gtk2 post glading, there is a lot less rebuilding.  We only
# need to edit gtk2-interface.c, adding a #if VERSION adn endif
# and also change support.h.gtk2 to support.h
