# geometry/Makefile.simple
# 
# Copyright 2002, 2003 The University of York
# Author: Paul Emsley
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA


# MMDB    = /y/people/emsley/autobuild/clipper/mmdb102
# CLIPPER = /y/people/emsley/autobuild/clipper

MMDB    = $(HOME)/crystal/clipper/mmdb
CLIPPER = $(HOME)/crystal/clipper


# Cambridge
# MMDB    = $(HOME)/build
# CLIPPER = $(HOME)/crystal/clipper
# MCCP4   = $(HOME)/crystal/clipper/mccp4-0.6.3
# FFTW    = $(HOME)/crystal/clipper/fftw

# York
# MMDB    = $(HOME)/mapview
# CLIPPER = $(HOME)/mapview
# CLIPPER = $(HOME)/test/install
# MCCP4   = $(HOME)/mapview

# Glasgow
MMDB    = $(HOME)/mapview
CLIPPER = $(HOME)/mapview
CLIPPER = $(HOME)/mapview
MCCP4   = $(HOME)/mapview


CXX = g++
MMDB_CXXFLAGS = -I$(MMDB)/include 
FFTW_LIBS = -L$(FFTW)/lib -lrfftw -lfftw

MMDB_LIBS = -L$(MMDB)/lib -lmmdb 
CLIPPER_LIBS = -L$(CLIPPER)/lib -lclipper-contrib \
	-lclipper-mtz -lclipper-phs -lclipper -L$(MCCP4)/lib -lmccp4 \
	-L$(CLIPPER)lib -L/h/paule/mapview/lib $(FFTW_LIBS)

MCCP4_CFLAGS = -I$(MCCP4)/include
CLIPPER_CXXFLAGS = -I$(CLIPPER)/include -I$(MCCP4)/include 

INCLUDES = $(CLIPPER_CXXFLAGS) $(MMDB_CXXFLAGS) -I$(top_srcdir)/coords 

top_srcdir = ..

OPTI = -g
CXXFLAGS = $(OPTI) $(INCLUDES)
LDLIBS   = -L$(top_srcdir)/coords -lcoot-coords $(CLIPPER_LIBS) $(MMDB_LIBS)

# $(GSL_LIBS)

testing: testing.o libcoot-protein-geometry.a
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS) $(TARGET_ARCH) $^ $(LOADLIBES) $(LDLIBS) -o $@

libcoot--geometry.a: protein-geometry.o
	ar r $@ $^

