
# to find clipper.pc, you will need to do something like
# export PKG_CONFIG_PATH=$COOT_DIR/lib/pkgconfig

COOT_DIR=$(HOME)/autobuild/Linux-pracaarch-gtk4

CXXFLAGS= \
   -I$(COOT_DIR)/include \
   -I$(COOT_DIR)/include/coot \
   `pkg-config --cflags gtk4` `pkg-config --cflags epoxy`  `pkg-config --cflags clipper` \
   -ggdb -O2 -march=native -std=c++17

LDLIBS=-fuse-ld=mold \
       -L$(COOT_DIR)/lib -lcoot-map-utils -lcoot-coord-utils -lcoot-geometry -lmmdb2 \
       `pkg-config --libs gtk4`  \
       `pkg-config --libs epoxy` \
       `pkg-config --libs clipper` \
        -g \
        -Wl,--rpath=$(COOT_DIR)/lib \
        -lfreetype -lm -ldl

gtk4-test-validation-graph: gtk4-test-validation-graph.cc
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDLIBS)

HEADERS = \
    residue-validation-information.hh \
    validation-information.hh

SOURCES = \
    residue-validation-information.cc \
    validation-information.cc \
    gtk4-test-validation-graph.cc

OBJS := $(patsubst %.cc,%.o,$(SOURCES))

%.cc: $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $@ -o $(patsubst %.cc,%.o,$@)

gtk4-test-validation-graph: $(OBJS) $(HEADERS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDLIBS)