

CLIPPER = /Users/paulemsley/ccp4/ysbl-distro-based

CLIPPER_CXXFLAGS = -I$(CLIPPER)/include

CLIPPER_LIBS = -L$(CLIPPER)/lib -lclipper-ccp4 \
	-lclipper-cif -lclipper-phs -lclipper-contrib -lclipper-mmdb \
	-lclipper-core -lccp4c -lmmdb -lm -lrfftw -lfftw -lz -lm

INCLUDES = -I../sec-str $(CLIPPER_CXXFLAGS)
LDLIBS = $(CLIPPER_LIBS)

.cc:
	$(CXX) $(INCLUDES) -o $@ $(LDLIBS) $^
