/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") residue_to_ligand_builder "

Parameters
----------
imol : int
chain_id : str
resno : int
ins_code : str
weight_for_3d_distances : float
";

%feature("docstring") smiles_to_ligand_builder "

Parameters
----------
smiles_string : str
";

