/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") make_directory_maybe "
make a directory dir (if it doesn't exist) and return error code

If it can be created, create the directory dir, return the success status like mkdir: mkdir

zero on success, or -1 if an error occurred. If dir already exists as a directory, return 0 of course.

Parameters
----------
dir : str
";

