/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") new_generic_object_number "
create a new generic object with name objname

return the index of the object

Parameters
----------
obj_name : str
";

%feature("docstring") new_generic_object_number_for_molecule "
create a new generic object with name objname and attach it to the given molecule

bool is_valid_generic_display_object_number(int obj); the index of the object

Parameters
----------
obj_name : str
imol : int
";

%feature("docstring") to_generic_object_add_line "
add line to generic object object_number

Parameters
----------
object_number : int
colour : str
line_width : int
to_x1 : float
to_y1 : float
to_z1 : float
to_x2 : float
to_y2 : float
to_z2 : float
";

%feature("docstring") to_generic_object_add_lines "
add multiple lines to generic object object_number

c.f. to_generic_object_add_points() each list item is a [colour, width, x1, y1, z1, x2, y2, z2]

Parameters
----------
object_number : int
line_info_list_py : object
";

%feature("docstring") to_generic_object_add_cylinder "

Parameters
----------
object_number : int
colour : str
line_radius : float
n_slices : int
from_x : float
from_y : float
from_z : float
to_x : float
to_y : float
to_z : float
cap_start : bool
cap_end : bool
";

%feature("docstring") to_generic_object_add_dashed_line "
add a dashed line to generic object object_number

dash_density is number of dashes per Angstrom.

Parameters
----------
object_number : int
colour : str
line_width : int
dash_density : float
from_x1 : float
from_y1 : float
from_z1 : float
to_x2 : float
to_y2 : float
to_z2 : float
";

%feature("docstring") to_generic_object_add_point "
add point to generic object object_number

Parameters
----------
object_number : int
colour : str
point_width : int
from_x1 : float
from_y1 : float
from_z1 : float
";

%feature("docstring") to_generic_object_add_points "

Parameters
----------
object_number : int
point_info_list_py : object
";

%feature("docstring") to_generic_object_add_point_internal "

Parameters
----------
object_number : int
colour_name : str
colour : const coot::colour_holder &
point_width : int
pt : const clipper::Coord_orth &
";

%feature("docstring") from_generic_object_remove_last_item "

Parameters
----------
object_number : int
";

%feature("docstring") to_generic_object_add_arc "
add point to generic object object_number

Parameters
----------
object_number : int
colour : str
radius : float
radius_inner : float
angle_delta : float
start_point_x : float
start_point_y : float
start_point_z : float
start_dir_x : float
start_dir_y : float
start_dir_z : float
normal_x1 : float
normal_y1 : float
normal_z1 : float
";

%feature("docstring") to_generic_object_add_torus "

Parameters
----------
object_number : int
colour_name : str
radius : float
radius_inner : float
centre_point_x : float
centre_point_y : float
centre_point_z : float
normal_x : float
normal_y : float
normal_z : float
";

%feature("docstring") to_generic_object_add_tori "
add multiple tori to generic object object_number

c.f. to_generic_object_add_lines() each list item is a [colour, radius, radius_inner, cx, cy, cz, nx, ny, nz]

Parameters
----------
object_number : int
torus_info_list_py : object
";

%feature("docstring") to_generic_object_add_arrow "

Parameters
----------
object_number : int
colour_name : str
stem_radius : float
from_x1 : float
from_y1 : float
from_z1 : float
to_x2 : float
to_y2 : float
to_z2 : float
";

%feature("docstring") to_generic_object_add_dodecahedron "

Parameters
----------
object_number : int
colour : str
radius : float
x : float
y : float
z : float
";

%feature("docstring") to_generic_object_add_pentakis_dodecahedron "

Parameters
----------
object_number : int
colour : str
stellation_factor : float
radius_factor : float
x : float
y : float
z : float
";

%feature("docstring") to_generic_object_add_mesh "

Parameters
----------
object_number : int
mesh_py : object
";

%feature("docstring") to_generic_object_attach_translation_gizmo "

Parameters
----------
object_number : int
";

%feature("docstring") generic_object_mesh_calculate_normals "

Parameters
----------
object_number : int
";

%feature("docstring") to_generic_object_add_display_list_handle "
add a display list handle generic object

Parameters
----------
object_number : int
display_list_id : int
";

%feature("docstring") set_display_generic_object "
set the display status of object number object_number,

when they are created, by default objects are not displayed, so we generally need this function.

Parameters
----------
object_number : int
istate : int
";

%feature("docstring") set_display_generic_object_simple "
set the display status of object number object_number,

set the state of a generic object to be drawn, but no redraw. Use when enabling multiple generic objects.

Parameters
----------
object_number : int
istate : int
";

%feature("docstring") generic_object_is_displayed_p "
is generic display object displayed?

1 for yes, otherwise 0

Parameters
----------
object_number : int
";

%feature("docstring") generic_object_index "
return the index of the object with name name, if not, return -1;

Parameters
----------
name : str
";

%feature("docstring") generic_object_name_scm "
what is the name of generic object number obj_number?

0 (NULL) (scheme False) on obj_number not available

Parameters
----------
obj_number : int
";

%feature("docstring") generic_object_name_py "

Parameters
----------
obj_number : int
";

%feature("docstring") get_generic_object_py "

Parameters
----------
obj_number : int
";

%feature("docstring") number_of_generic_objects "
return the number of generic display objects
";

%feature("docstring") generic_object_info "
print to the console the name and display status of the generic display objects
";

%feature("docstring") get_generic_object_info "
get generic display objects

Parameters
----------
obj_number : int
";

%feature("docstring") generic_object_has_objects_p "
does generic display object number obj_no have things to display? (predicate name)

0 for no things, 1 for things.

Parameters
----------
obj_no : int
";

%feature("docstring") close_generic_object "
close generic object

clear the lines/points etc, not available for buttons/displaying etc

param obj_number the object_number of the generic object to close

Parameters
----------
object_number : int
";

%feature("docstring") is_closed_generic_object_p "
has the generic object been closed?

1 for yes, 0 othersize

Parameters
----------
object_number : int
";

%feature("docstring") generic_object_clear "
clear out the lines and points from object_number, but keep it displayable (not closed).

Parameters
----------
object_number : int
";

%feature("docstring") attach_generic_object_to_molecule "
attach the generic object to a particular molecule

one might do this if the generic object is specific to a molecule.

Parameters
----------
obj_number : int
imol : int
";

