/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") associate_pir_alignment "
associate an alignment with a chain in a model molecule

The pir_alignment is a string (with newlines)

Parameters
----------
imol : int
chain_id : str
pir_alignment : str
";

%feature("docstring") associate_pir_alignment_from_file "
associate an alignment in a file with a chain in a model molecule

Parameters
----------
imol : int
chain_id : str
pir_alignment_file_name : str
";

%feature("docstring") apply_pir_alignment "
apply the mutations of the associated alignment

Parameters
----------
imol : int
chain_id : str
";

