/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") make_ncs_maps "

Parameters
----------
imol_model : int
imol_map : int
";

%feature("docstring") ncs_ligand "
Make NCS-related copies of a ligand.

Given a ligand near the NCS master chain, use the NCS operators to generate copies of the ligand positioned near each peer chain. Returns a vector of molecule numbers for the newly created ligand copies.

Parameters
----------
imol_protein : int
ncs_master_chain_id : str
imol_ligand : int
chain_id_ligand : str
resno_ligand_start : int
resno_ligand_stop : int
";

