/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") probe_clash_score_scm "
return scheme false on failure or a scheme list

Parameters
----------
dots_file_name : str
";

%feature("docstring") probe_clash_score_as_scm "

Parameters
----------
p : str
";

%feature("docstring") probe_clash_score_from_scm "

Parameters
----------
p : SCM
";

%feature("docstring") probe_clash_score_py "
return scheme false on failure or a scheme list

Parameters
----------
dots_file_name : str
";

%feature("docstring") probe_clash_score_as_py "

Parameters
----------
p : str
";

%feature("docstring") probe_clash_score_from_py "

Parameters
----------
p : object
";

