/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") set_mark_cis_peptides_as_bad "

Parameters
----------
istate : int
";

%feature("docstring") show_hide_preferences_tabs "

Parameters
----------
toggletoolbutton : GtkToggleButton *
preference_type : int
";

%feature("docstring") show_hide_preferences_tabs "

Parameters
----------
toggletoolbutton : GtkToggleToolButton *
preference_type : int
";

%feature("docstring") preferences_internal_change_value_int "

Parameters
----------
preference_type : int
ivalue : int
";

%feature("docstring") preferences_internal_change_value_int2 "

Parameters
----------
preference_type : int
ivalue1 : int
ivalue2 : int
";

%feature("docstring") preferences_internal_change_value_float "

Parameters
----------
preference_type : int
fvalue : float
";

%feature("docstring") preferences_internal_change_value_float3 "

Parameters
----------
preference_type : int
fvalue1 : float
fvalue2 : float
fvalue3 : float
";

%feature("docstring") show_model_toolbar_icon "

Parameters
----------
pos : int
";

%feature("docstring") hide_model_toolbar_icon "

Parameters
----------
pos : int
";

%feature("docstring") show_main_toolbar_icon "

Parameters
----------
pos : int
";

%feature("docstring") hide_main_toolbar_icon "

Parameters
----------
pos : int
";

%feature("docstring") fill_preferences_model_toolbar_icons "

Parameters
----------
preferences : GtkWidget *
scrolled_window : GtkWidget *
";

%feature("docstring") fill_preferences_main_toolbar_icons "

Parameters
----------
preferences : GtkWidget *
scrolled_window : GtkWidget *
";

