/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") read_shelx_ins_file "
read a SHELXL .ins file

Parameters
----------
filename : str
recentre_flag : short int
";

%feature("docstring") write_shelx_ins_file "
write a SHELXL .ins file for molecule number imol

Parameters
----------
imol : int
filename : const char *
";

%feature("docstring") handle_shelx_fcf_file_internal "

Parameters
----------
filename : const char *
";

%feature("docstring") chain_id_for_shelxl_residue_number "
the chain id for the given residue. false if can't do it/fail.

Parameters
----------
imol : int
resno : int
";

%feature("docstring") is_shelx_molecule "

Parameters
----------
imol : int
";

%feature("docstring") chain_id_for_shelxl_residue_number_py "
the chain id for the given residue. Return Py_False if can't do it/fail.

Parameters
----------
imol : int
resno : int
";

%feature("docstring") add_shelx_string_to_molecule "

Parameters
----------
imol : int
string : const char *
";

%feature("docstring") handle_read_draw_molecule_with_recentre "
read coordinates from filename with option to not recentre.

set recentre_on_read_pdb_flag to 0 if you don't want the view to recentre on the new coordinates.

Parameters
----------
filename : str
recentre_on_read_pdb_flag : int
";

%feature("docstring") handle_read_draw_molecule_and_move_molecule_here "
read coordinates from filename and recentre the new molecule at the screen rotation centre.

Parameters
----------
filename : str
";

%feature("docstring") read_pdb "
read coordinates from filename

Parameters
----------
filename : str
";

%feature("docstring") read_coordinates "
read coordinates from filename

  filename  is the file name of the coordinates the new molecule index. Return -1 on failure

Parameters
----------
filename : str
    is the file name of the coordinates
";

%feature("docstring") read_coordinates_as_string "
read coordinates from a string

  file_as_string  a string which is the contents of a file the new molecule index. Return -1 on failure

Parameters
----------
file_as_string : str
    a string which is the contents of a file
";

%feature("docstring") handle_read_draw_molecule "
a synonym for read-pdb. Read the coordinates from filename (can be pdb, cif or shelx format)

Parameters
----------
filename : str
";

%feature("docstring") set_use_gemmi_as_model_molecule_parser "
set (or unset) GEMMI as the molecule parser. Currently by passing an int.

Parameters
----------
state : int
";

