/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */
/* Include this file in your main .i file with: %include "coot_docstrings.i" */

%feature("docstring") get_symmetry "
return the symmetry of the imolth molecule

Return as a list of strings the symmetry operators of the given molecule. If imol is a not a valid molecule, return an empty list.*

Parameters
----------
imol : int
";

%feature("docstring") get_symmetry_py "
return the symmetry of the imolth molecule

Return as a list of strings the symmetry operators of the given molecule. If imol is a not a valid molecule, return an empty list.*

Parameters
----------
imol : int

Returns
-------
object
    a python object as a list (or some other python container)
";

%feature("docstring") clashes_with_symmetry "
return 1 if this residue clashes with the symmetry-related atoms of the same molecule.

0 means that it did not clash, -1 means that the residue or molecule could not be found or that there was no cell and symmetry.

Parameters
----------
imol : int
chain_id : const char *
res_no : int
ins_code : const char *
clash_dist : float
";

%feature("docstring") add_molecular_symmetry "
Add molecular symmetry

You will need to know how to expand your point group molecular symmetry to a set of 3x3 matrices. Call this function for every matrix.

Parameters
----------
imol : int
r_00 : float
r_01 : float
r_02 : float
r_10 : float
r_11 : float
r_12 : float
r_20 : float
r_21 : float
r_22 : float
about_origin_x : float
about_origin_y : float
about_origin_z : float
";

%feature("docstring") add_molecular_symmetry_from_mtrix_from_file "
Add molecular symmetry.

Often molecular symmetry is descibed using MTRIX card in a PDB file header. Use this function to extract and apply such molecular symmmetry

Parameters
----------
imol : int
file_name : str
";

%feature("docstring") add_molecular_symmetry_from_mtrix_from_self_file "
Add molecular symmetry

This is a convenience function for the above - where you don't need to specify the PDB file name.

Parameters
----------
imol : int
";

%feature("docstring") auto_read_make_and_draw_maps "
read MTZ file filename and from it try to make maps

Useful for reading the output of refmac. The default labels (FWT/PHWT and DELFWT/PHDELFWT) can be changed using ...[something]

Parameters
----------
filename : const char *

Returns
-------
std::vector< int >
    a list of molecule numbers for the new maps
";

%feature("docstring") auto_read_make_and_draw_maps_from_mtz "
set the flag to do a difference map (too) on auto-read MTZ

Parameters
----------
file_name : str
";

%feature("docstring") auto_read_make_and_draw_maps_from_cns "

Parameters
----------
file_name : str
";

%feature("docstring") valid_labels "
does the mtz file have the columms that we want it to have?

Parameters
----------
mtz_file_name : str
f_col : str
phi_col : str
weight_col : str
use_weights_flag : bool
";

%feature("docstring") sharpen_blur_map "
make a sharpened or blurred map

blurred maps are generated by using a positive value of b_factor.

Parameters
----------
imol_map : int
b_factor : float

Returns
-------
int
    the index of the map created by applying a b-factor to the given map. Return -1 on failure.
";

%feature("docstring") sharpen_blur_map_with_resampling "
make a sharpened or blurred map with resampling

resampling factor might typically be 1.3

blurred maps are generated by using a positive value of b_factor.

Parameters
----------
imol_map : int
b_factor : float
resample_factor : float

Returns
-------
int
    the index of the map created by applying a b-factor to the given map. Return -1 on failure.
";

%feature("docstring") sharpen_blur_map_with_resampling_threaded_version "

Parameters
----------
imol_map : int
b_factor : float
resample_factor : float
";

%feature("docstring") multi_sharpen_blur_map_scm "
make many sharpened or blurred maps

blurred maps are generated by using a positive value of b_factor.

Parameters
----------
imol_map : int
b_factors_list : SCM
";

%feature("docstring") multi_sharpen_blur_map_py "
make many sharpened or blurred maps

blurred maps are generated by using a positive value of b_factor.

Parameters
----------
imol_map : int
b_factors_list : object
";

%feature("docstring") amplitude_vs_resolution_py "

Parameters
----------
mol_map : int
";

%feature("docstring") amplitude_vs_resolution_scm "

Parameters
----------
mol_map : int
";

%feature("docstring") flip_hand "
Flip the hand of the map.

in case it was accidentally generated on the wrong one.

Parameters
----------
imol_map : int

Returns
-------
int
    the molecule number of the flipped map.
";

%feature("docstring") analyse_map_point_density_change "
test function for analysis of multiple map

Parameters
----------
map_number_list : const std::vector< int > &
imol_map_mask : int
";

%feature("docstring") analyse_map_point_density_change_py "

Parameters
----------
map_number_list : object
imol_map_mask : int
";

%feature("docstring") go_to_map_molecule_centre "
Go to the centre of the molecule - for Cryo-EM Molecules.

Parameters
----------
imol_map : int
";

%feature("docstring") b_factor_from_map "
b-factor from map

calculate structure factors and use the amplitudes to estimate the B-factor of the data using a wilson plot using a low resolution limit of 4.5A.

Parameters
----------
imol_map : int

Returns
-------
float
    -1 when given a bad map or there were no data beyond 4.5A
";

%feature("docstring") map_colour_components "
return the colour triple of the imolth map

(e.g.: (list 0.4 0.6 0.8). If invalid imol return scheme false.

Parameters
----------
imol : int
";

%feature("docstring") map_colour_components_py "
return the colour triple of the imolth map

e.g.: [0.4, 0.6, 0.8]. If invalid imol return Py_False.

Parameters
----------
imol : int
";

%feature("docstring") read_ccp4_map "
read a CCP4 map or a CNS map (despite the name).

Parameters
----------
filename : str
is_diff_map_flag : int
";

%feature("docstring") handle_read_ccp4_map "
same function as above - old name for the function. Deleted from the API at some stage

Parameters
----------
filename : str
is_diff_map_flag : int
";

%feature("docstring") handle_read_emdb_data "
this reads a EMDB bundle - I don't think they exist any more

Parameters
----------
dir_name : str
";

%feature("docstring") map_partition_by_chain "
Use the function for scriptng.

Parameters
----------
imol_map : int
imol_model : int
";

%feature("docstring") map_partition_by_chain_threaded "
Use the function for use in the GUI (non-blocking, no results returned)

Parameters
----------
imol_map : int
imol_model : int
";

%feature("docstring") set_use_vertex_gradients_for_map_normals "

Parameters
----------
imol : int
state : int
";

%feature("docstring") use_vertex_gradients_for_map_normals_for_latest_map "
the map should be displayed and not a difference map
";

%feature("docstring") set_use_vertex_gradients_for_map_normals_for_latest_map "
alias for the above (more canonical naming)
";

%feature("docstring") multi_residue_torsion_fit_scm "
fit residues

(note: fit to the current-refinement map)

Parameters
----------
imol : int
residues_specs_scm : SCM
n_trials : int
";

%feature("docstring") multi_residue_torsion_fit "

Parameters
----------
imol : int
specs : const std::vector< coot::residue_spec_t > &
n_trials : int
";

%feature("docstring") multi_residue_torsion_fit_py "
fit residues

(note: fit to the current-refinement map)

Parameters
----------
imol : int
residues_specs_py : object
n_trials : int
";

%feature("docstring") add_an_atom "

Parameters
----------
element : str
";

%feature("docstring") nudge_the_temperature_factors_py "

Parameters
----------
imol : int
residue_spec_py : object
amount : float
";

%feature("docstring") merge_fragments "
each fragment is presumed to be in its own chain.

Parameters
----------
imol : int
";

%feature("docstring") delete_chain "
delete the chain

Parameters
----------
imol : int
chain_id : str
";

%feature("docstring") delete_sidechains_for_chain "
delete the side chains in the chain

Parameters
----------
imol : int
chain_id : str
";

%feature("docstring") execute_refmac_real "
if swap_map_colours_post_refmac_flag is not 1 thenn imol_refmac_map is ignored.

Parameters
----------
pdb_in_filename : str
pdb_out_filename : str
mtz_in_filename : str
mtz_out_filename : str
cif_lib_filename : str
fobs_col_name : str
sigfobs_col_name : str
r_free_col_name : str
have_sensible_free_r_flag : short int
make_molecules_flag : short int
refmac_count_string : str
swap_map_colours_post_refmac_flag : int
imol_refmac_map : int
diff_map_flag : int
phase_combine_flag : int
phib_string : str
fom_string : str
ccp4i_project_dir : str
";

%feature("docstring") refmac_name "
the name for refmac

Parameters
----------
imol : int

Returns
-------
str
    a stub name used in the construction of filename for refmac output
";

%feature("docstring") handle_cif_dictionary "

Parameters
----------
filename : str
";

%feature("docstring") read_cif_dictionary "

Parameters
----------
filename : str
";

%feature("docstring") handle_cif_dictionary_for_molecule "

Parameters
----------
filename : str
imol_enc : int
new_molecule_from_dictionary_cif_checkbutton_state : short int
";

%feature("docstring") dictionary_entries "
dictionary entries
";

%feature("docstring") debug_dictionary "
debug dictionary information
";

%feature("docstring") get_types_in_molecule "
get types in molecule

:param imol: the molecule index

Parameters
----------
imol : int

Returns
-------
std::vector< std::string >
    a vector of residue types
";

%feature("docstring") SMILES_for_comp_id "
Get the SMILES for the given residue type

:param comp_id: is the residue type

Parameters
----------
comp_id : str

Returns
-------
str
    the SMILES string
";

%feature("docstring") dictionaries_read "
return a list of all the dictionaries read
";

%feature("docstring") cif_file_for_comp_id_scm "

Parameters
----------
comp_id : str
";

%feature("docstring") SMILES_for_comp_id_scm "

Parameters
----------
comp_id : str
";

%feature("docstring") cif_file_for_comp_id_py "

Parameters
----------
comp_id : str
";

%feature("docstring") SMILES_for_comp_id_py "
Get the SMILES for the given residue type.

:param comp_id: is the residue type

Parameters
----------
comp_id : str

Returns
-------
object
    the SMILES string or False on failure to find the residue type or SMILES string
";

%feature("docstring") monomer_restraints "
return the monomer restraints for the given monomer_type, return scheme false on \"restraints for monomer not found\"

Parameters
----------
monomer_type : const char *
";

%feature("docstring") set_monomer_restraints "
set the monomer restraints of the given monomer_type

Parameters
----------
monomer_type : const char *
restraints : SCM

Returns
-------
SCM
    scheme false or true for success or failure to set the restrains for monomer_type *
";

%feature("docstring") monomer_restraints_py "

Parameters
----------
monomer_type : str
";

%feature("docstring") monomer_restraints_for_molecule_py "

Parameters
----------
monomer_type : str
imol : int
";

%feature("docstring") set_monomer_restraints_py "

Parameters
----------
monomer_type : const char *
restraints : object
";

%feature("docstring") show_restraints_editor "
show restraints editor

Parameters
----------
monomer_type : str
";

%feature("docstring") show_restraints_editor_by_index "

Parameters
----------
menu_item_index : int
";

%feature("docstring") write_restraints_cif_dictionary "
write cif restraints for monomer

Parameters
----------
monomer_type : str
file_name : str
";

%feature("docstring") atom_info_string_scm "
output atom info in a scheme list for use in scripting

in this format (list occ temp-factor element x y z). Return empty list if atom not found. *

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
atname : const char *
altconf : const char *
";

%feature("docstring") molecule_to_pdb_string_scm "

Parameters
----------
imol : int
";

%feature("docstring") resname_from_serial_number "
return the rename from a residue serial number

Parameters
----------
imol : int
chain_id : const char *
serial_num : int

Returns
-------
str
    blank (\"\") on failure.
";

%feature("docstring") residue_name "
return the residue name of the specified residue

Parameters
----------
imol : int
chain_id : str
resno : int
ins_code : str
";

%feature("docstring") serial_number_from_residue_specs "
return the serial number of the specified residue

Parameters
----------
imol : int
chain_id : str
res_no : int
ins_code : str

Returns
-------
int
    -1 on failure to find the residue
";

%feature("docstring") residue_info "
Return a list of atom info for each atom in the specified residue.

output is like this: (list (list (list atom-name alt-conf) (list occ temp-fact element) (list x y z)))

occ can be a single number or a list of seven numbers of which the first is the isotropic B.

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
";

%feature("docstring") residue_name_scm "

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
";

%feature("docstring") chain_fragments_scm "
chain fragments

Parameters
----------
imol : int
screen_output_also : short int
";

%feature("docstring") add_molecule "
generate a molecule from an s-expression

return a molecule number, -1 on error

Parameters
----------
molecule_expression : SCM
name : const char *
";

%feature("docstring") clear_and_update_molecule "
update a molecule from a s-expression

And going the other way, given an s-expression, update molecule_number by the given molecule. Clear what's currently there first though.

Parameters
----------
molecule_number : int
molecule_expression : SCM
";

%feature("docstring") active_residue "
return specs of the atom close to screen centre

Return a list of (list imol chain-id resno ins-code atom-name alt-conf) for atom that is closest to the screen centre in any displayed molecule. If there are multiple models with the same coordinates at the screen centre, return the attributes of the atom in the highest number molecule number.

return scheme false if no active residue
";

%feature("docstring") closest_atom_simple_scm "
return the specs of the closest displayed atom

Return a list of (list imol chain-id resno ins-code atom-name alt-conf (list x y z)) for atom that is closest to the screen centre in the given molecule (unlike active-residue, potential CA substition is not performed). If there is no atom, or if imol is not a valid model molecule, return scheme false.
";

%feature("docstring") closest_atom "
return the specs of the closest atom in imolth molecule

Return a list of (list imol chain-id resno ins-code atom-name alt-conf (list x y z)) for atom that is closest to the screen centre in the given molecule (unlike active-residue, no account is taken of the displayed state of the molecule). If there is no atom, or if imol is not a valid model molecule, return scheme false.

Parameters
----------
imol : int
";

%feature("docstring") closest_atom_raw_scm "
return the specs of the closest atom to the centre of the screen

Return a list of (list imol chain-id resno ins-code atom-name alt-conf (list x y z)) for atom that is closest to the screen for displayed molecules. If there is no atom, return scheme false. Don't choose the CA of the residue if there is a CA in the residue of the closest atom. 201602015-PE: I add this now, but I have a feeling that I've done this before.
";

%feature("docstring") residues_near_residue "
return residues near residue

Return residue specs for residues that have atoms that are closer than radius Angstroems to any atom in the residue specified by res_in.

Parameters
----------
imol : int
residue_in_scm : SCM
radius : float
";

%feature("docstring") residues_near_residues_scm "
return residues near the given residues

Return residue specs for residues that have atoms that are closer than radius Angstroems to any atom in the residue specified by res_in.

Parameters
----------
imol : int
residues_in : SCM
radius : float
";

%feature("docstring") residues_near_position_scm "
residues near residue

Parameters
----------
imol : int
pos : SCM
radius : float

Returns
-------
SCM
    residues within radius of pos (x,y,z) position
";

%feature("docstring") label_closest_atoms_in_neighbour_residues_scm "
label the closest atoms in the residues that neighbour residue_spec

Parameters
----------
imol : int
residue_spec_scm : SCM
radius : float
";

%feature("docstring") hydrogenate_region "
find the active residue, find the near residues (within radius) create a new molecule, run reduce on that, import hydrogens from the result and apply them to the molecule of the active residue.

Parameters
----------
radius : float
";

%feature("docstring") add_hydrogens_from_file "
Add hydrogens to imol from the given pdb file.

Parameters
----------
imol : int
pdb_with_Hs_file_name : str
";

%feature("docstring") add_hydrogen_atoms_to_residue "
add hydrogen atoms to the specified residue

Parameters
----------
imol : int
chain_id : str
res_no : int
ins_code : str
";

%feature("docstring") add_hydrogen_atoms_to_residue_py "
add hydrogen atoms to the specified residue

Parameters
----------
imol : int
residue_spec_py : object
";

%feature("docstring") atom_info_string_py "
output atom info in a python list for use in scripting:

in this format [occ, temp_factor, element, x, y, z]. Return empty list if atom not found. *

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
atname : const char *
altconf : const char *
";

%feature("docstring") molecule_to_pdb_string_py "
Return the molecule as a PDB string.

Parameters
----------
imol : int
";

%feature("docstring") residue_info_py "
Return a list of atom info for each atom in the specified residue:

output is like this: [ [[atom-name,alt-conf] [occ,temp_fact,element] [x,y,z]]]

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
";

%feature("docstring") residue_name_py "

Parameters
----------
imol : int
chain_id : const char *
resno : int
ins_code : const char *
";

%feature("docstring") residue_centre_from_spec_py "

Parameters
----------
imol : int
spec_py : object
";

%feature("docstring") chain_fragments_py "

Parameters
----------
imol : int
screen_output_also : short int
";

%feature("docstring") set_b_factor_residues_py "

Parameters
----------
imol : int
residue_specs_b_value_tuple_list_py : object
";

%feature("docstring") set_b_factor_residues_scm "

Parameters
----------
imol : int
residue_specs_b_value_tuple_list_scm : SCM
";

%feature("docstring") clear_and_update_molecule_py "

Parameters
----------
molecule_number : int
molecule_expression : object
";

%feature("docstring") add_molecule_py "

Parameters
----------
molecule_expression : object
name : const char *
";

%feature("docstring") active_residue_py "
Return a list of [imol, chain-id, resno, ins-code, atom-name, alt-conf] for atom that is closest to the screen centre. If there are multiple models with the same coordinates at the screen centre, return the attributes of the atom in the highest number molecule number.

return False if no active residue
";

%feature("docstring") closest_atom_simple_py "
return the spec of the closest displayed atom

Return a list of [imol, chain-id, resno, ins-code, atom-name, alt-conf, [x, y, z]] for atom that is closest to the screen centre in the given molecule (unlike active-residue, potential CA substition is not performed). If there is no atom, or if imol is not a valid model molecule, return False.
";

%feature("docstring") closest_atom_py "
return closest atom in imolth molecule

Return a list of [imol, chain-id, resno, ins-code, atom-name, alt-conf, [x, y, z]] for atom that is closest to the screen centre in the given molecule (unlike active-residue, no account is taken of the displayed state of the molecule). If there is no atom, or if imol is not a valid model molecule, return False.

Parameters
----------
imol : int
";

%feature("docstring") closest_atom_raw_py "
return the specs of the closest atom to the centre of the screen

Return a list of (list imol chain-id resno ins-code atom-name alt-conf (list x y z)) for atom that is closest to the screen for displayed molecules. If there is no atom, return scheme false. Don't choose the CA of the residue if there is a CA in the residue of the closest atom
";

%feature("docstring") residues_near_residue_py "

Parameters
----------
imol : int
residue_in : object
radius : float
";

%feature("docstring") residues_near_residues_py "

Parameters
----------
imol : int
residues_in : object
radius : float
";

%feature("docstring") residues_near_position_py "
Return residue specs for residues that have atoms that are closer than radius Angstroems to the given position.

Parameters
----------
imol : int
pos_in : object
radius : float
";

%feature("docstring") label_closest_atoms_in_neighbour_residues_py "
label the closest atoms in the residues that neighbour residue_spec

Parameters
----------
imol : int
residue_spec_py : object
radius : float
";

%feature("docstring") get_bonds_representation "
return a Python object for the bonds

Parameters
----------
imol : int
";

%feature("docstring") set_new_non_drawn_bonds "
replace any current non-drawn bonds with these - and regen bonds

Parameters
----------
imol : int
cid : str
";

%feature("docstring") add_to_non_drawn_bonds "
add to non-drawn bonds - and regen bonds

Parameters
----------
imol : int
cid : str
";

%feature("docstring") clear_non_drawn_bonds "
clear the non-drawn bonds - force regen bonds to restore all

Parameters
----------
imol : int
";

%feature("docstring") get_dictionary_radii "
return a Python object for the radii of the atoms in the dictionary
";

%feature("docstring") get_environment_distances_representation_py "
return a Python object for the representation of bump and hydrogen bonds oft

Parameters
----------
imol : int
residue_spec_py : object
";

%feature("docstring") get_intermediate_atoms_bonds_representation "
return a Python object for the intermediate atoms bonds
";

%feature("docstring") get_continue_updating_refinement_atoms_state "
return the continue-updating-refinement-atoms state
";

%feature("docstring") atom_info_as_text_for_statusbar "

Parameters
----------
atom_index : int
imol : int
";

%feature("docstring") atom_info_as_text_for_statusbar "

Parameters
----------
atom_index : int
imol : int
sts : const std::pair< symm_trans_t, Cell_Translation > &
";

%feature("docstring") all_residues_with_serial_numbers_scm "
a utility to return the specs of all the residues, each spec prefixed by the serial number

Parameters
----------
imol : int
";

%feature("docstring") all_residues_with_serial_numbers_py "

Parameters
----------
imol : int
";

%feature("docstring") regularize_residues "
regularize the given residues

Parameters
----------
imol : int
residues : const std::vector< coot::residue_spec_t > &
";

%feature("docstring") mtz_file_name "
presumes that imol_Refinement_Map has been set

Parameters
----------
imol : int
";

%feature("docstring") refine_zone_with_full_residue_spec_scm "
Refine the given residue range.

Parameters
----------
imol : int
chain_id : const char *
resno1 : int
inscode_1 : const char *
resno2 : int
inscode_2 : const char *
altconf : const char *
";

%feature("docstring") refine_zone_with_full_residue_spec_py "

Parameters
----------
imol : int
chain_id : const char *
resno1 : int
inscode_1 : const char *
resno2 : int
inscode_2 : const char *
altconf : const char *
";

%feature("docstring") set_draw_moving_atoms_rota_markup "
set display of rotamer markup during interactive real space refinement

Parameters
----------
state : short int
";

%feature("docstring") set_draw_moving_atoms_rama_markup "
set display of ramachandran markup during interactive real space refinement

Parameters
----------
state : short int
";

%feature("docstring") set_show_intermediate_atoms_rota_markup "
the old names for the above functions:

Parameters
----------
state : short int
";

%feature("docstring") set_show_intermediate_atoms_rama_markup "
the old names for the above functions:

Parameters
----------
state : short int
";

%feature("docstring") get_draw_moving_atoms_rota_markup_state "
the geters for the rota markup
";

%feature("docstring") get_draw_moving_atoms_rama_markup_state "
the geters for the rama markup
";

%feature("docstring") get_show_intermediate_atoms_rota_markup "
the old names for the above functions:
";

%feature("docstring") get_show_intermediate_atoms_rama_markup "
the old names for the above functions:
";

%feature("docstring") set_cryo_em_refinement "

Parameters
----------
mode : bool
";

%feature("docstring") accept_moving_atoms_py "
Accept moving atoms

This waits for the refinement to finish and then accepts the moving atoms so that they move into the main molecule.
";

%feature("docstring") register_post_intermediate_atoms_moved_hook "

Parameters
----------
function_name : object
";

%feature("docstring") set_regenerate_bonds_needs_make_bonds_type_checked "

Parameters
----------
state : bool
";

%feature("docstring") water_chain_from_shelx_ins_scm "
return the chain id of the water chain from a shelx molecule. Raw interface

Parameters
----------
imol : int

Returns
-------
SCM
    scheme false if no chain or bad imol
";

%feature("docstring") water_chain_scm "
return the chain id of the water chain. Raw interface

Parameters
----------
imol : int
";

%feature("docstring") water_chain_from_shelx_ins_py "

Parameters
----------
imol : int
";

%feature("docstring") water_chain_py "
return the chain id of the water chain. Raw interface

Parameters
----------
imol : int
";

%feature("docstring") add_status_bar_text "
Put text s into the status bar.

use this to put info for the user in the statusbar (less intrusive than popup).

Parameters
----------
s : str
";

%feature("docstring") set_logging_level "
set the logging level

:param level: is either \"LOW\" or \"HIGH\" or \"DEBUGGING\"

Parameters
----------
level : str
";

%feature("docstring") print_glyco_tree "
print the glycosylation tree that contains the specified residue

Parameters
----------
imol : int
chain_id : str
resno : int
ins_code : str
";

%feature("docstring") make_variance_map "

Parameters
----------
map_molecule_number_vec : const std::vector< int > &
";

%feature("docstring") make_variance_map_scm "

Parameters
----------
map_molecule_number_list : SCM
";

%feature("docstring") make_variance_map_py "

Parameters
----------
map_molecule_number_list : object
";

%feature("docstring") spin_search_by_atom_vectors "

Parameters
----------
imol_map : int
imol : int
chain_id : str
resno : int
ins_code : str
direction_atoms_list : const std::pair< std::string, std::string > &
moving_atoms_list : list
";

%feature("docstring") spin_search "
for the given residue, spin the atoms in moving_atom_list around the bond defined by direction_atoms_list looking for the best fit to density of imol_map map of the first atom in moving_atom_list. Works (only) with atoms in altconf \"\"

Parameters
----------
imol_map : int
imol : int
chain_id : const char *
resno : int
ins_code : const char *
direction_atoms_list : SCM
moving_atoms_list : SCM
";

%feature("docstring") spin_N_scm "
Spin N and CB (and the rest of the side chain if extant)

Sometime on N-terminal addition, then N ends up pointing the wrong way. The allows us to (more or less) interchange the positions of the CB and the N. angle is in degrees.

Parameters
----------
imol : int
residue_spec_scm : SCM
angle : float
";

%feature("docstring") CG_spin_search_scm "
Spin search the density based on possible positions of CG of a side-chain.

c.f. EM-Ringer

Parameters
----------
imol_model : int
imol_map : int
";

%feature("docstring") spin_search_py "
for the given residue, spin the atoms in moving_atom_list...

around the bond defined by direction_atoms_list looking for the best fit to density of imom_map map of the first atom in moving_atom_list. Works (only) with atoms in altconf \"\"

Parameters
----------
imol_map : int
imol : int
chain_id : const char *
resno : int
ins_code : const char *
direction_atoms_list : object
moving_atoms_list : object
";

%feature("docstring") spin_N_py "
Spin N and CB (and the rest of the side chain if extant)

Sometime on N-terminal addition, then N ends up pointing the wrong way. The allows us to (more or less) interchange the positions of the CB and the N. angle is in degrees.

:param imol: is the index of the model molecule 
:param residue_spec: is the specifier for the residue 
:param angle: is the rotation angle, in degrees, typically 120.

Parameters
----------
imol : int
residue_spec : object
angle : float
";

%feature("docstring") CG_spin_search_py "
Spin search the density based on possible positions of CG of a side-chain

:param imol_model: is the index of the model molecule 
:param imol_map: is the index of the map molecule

Parameters
----------
imol_model : int
imol_map : int

Returns
-------
object
    either False (in the case of a failure) or a list of pairs of residue specifers and score - for each spinnable residue in the model.
";

%feature("docstring") ligand_search_make_conformers_scm "
make conformations

as if for a ligand search

Don't search the density.

Returns
-------
SCM
    a list of new molecule numbers
";

%feature("docstring") cootaneer "
cootaneer (i.e. assign sidechains onto mainchain model)

atom_in_fragment_atom_spec is any atom spec in the fragment that should be assigned with sidechains.

Parameters
----------
imol_map : int
imol_model : int
atom_in_fragment_atom_spec : SCM

Returns
-------
int
    the success status (0 is fail).
";

%feature("docstring") cootaneer_py "
cootaneer (i.e. assign sidechains onto mainchain model)

atom_in_fragment_atom_spec is any atom spec in the fragment that should be assigned with sidechains.

Parameters
----------
imol_map : int
imol_model : int
atom_in_fragment_atom_spec : object

Returns
-------
int
    the success status (0 is fail).
";

%feature("docstring") sequence_from_map "

Parameters
----------
imol : int
chain_id : str
resno_start : int
resno_end : int
imol_map : int
";

%feature("docstring") apply_sequence_to_fragment "

Parameters
----------
imol : int
chain_id : str
resno_start : int
resno_end : int
imol_map : int
file_name_for_sequences : str
";

%feature("docstring") score_rotamers "

Parameters
----------
imol : int
chain_id : const char *
res_no : int
ins_code : const char *
alt_conf : const char *
imol_map : int
clash_flag : int
lowest_probability : float
";

%feature("docstring") score_rotamers_scm "
return the scores of the rotamers for this residue.

Parameters
----------
imol : int
chain_id : const char *
res_no : int
ins_code : const char *
alt_conf : const char *
imol_map : int
clash_flag : int
lowest_probability : float
";

%feature("docstring") score_rotamers_py "

Parameters
----------
imol : int
chain_id : const char *
res_no : int
ins_code : const char *
alt_conf : const char *
imol_map : int
clash_flag : int
lowest_probability : float
";

%feature("docstring") protein_db_loops "
Cowtan's protein_db loops.

Parameters
----------
imol_coords : int
residue_specs : const std::vector< coot::residue_spec_t > &
imol_map : int
nfrags : int
preserve_residue_names : bool
";

%feature("docstring") protein_db_loop_specs_to_atom_selection_string "

Parameters
----------
specs : const std::vector< coot::residue_spec_t > &
";

%feature("docstring") protein_db_loops_scm "

Parameters
----------
imol_coords : int
residues_specs : SCM
imol_map : int
nfrags : int
preserve_residue_names : bool
";

%feature("docstring") protein_db_loops_py "

Parameters
----------
imol_coords : int
residues_specs : object
imol_map : int
nfrags : int
preserve_residue_names : bool
";

%feature("docstring") hole "
starting point and end point, colour map multiplier and shall the probe radius graph be shown (dummy value currently).

if export_dots_file_name string length is zero, then don't try to export the surface dots.

Parameters
----------
imol : int
start_x : float
start_y : float
start_z : float
end_x : float
end_y : float
end_z : float
colour_map_multiplier : float
colour_map_offset : float
n_runs : int
show_probe_radius_graph_flag : bool
export_surface_dots_file_name : str
";

%feature("docstring") gaussian_surface "
The surface is separated into chains to make Generid Display Objects There is no colour, contour, grid or sigma or material control yet for Gaussian surfaces.

there should be one day...

Parameters
----------
imol : int
";

%feature("docstring") set_gaussian_surface_sigma "
set the sigma for gaussian surface (default 4.0)

Parameters
----------
s : float
";

%feature("docstring") set_gaussian_surface_contour_level "
set the contour_level for gaussian surface (default 4.4)

Parameters
----------
s : float
";

%feature("docstring") set_gaussian_surface_box_radius "
set the box_radius for gaussian surface (defautl 5)

Parameters
----------
s : float
";

%feature("docstring") set_gaussian_surface_grid_scale "
set the grid_scale for gaussian surface (default 0.7)

Parameters
----------
s : float
";

%feature("docstring") set_gaussian_surface_fft_b_factor "
set the fft B-factor for gaussian surface. Use 0 for no B-factor (default 100)

Parameters
----------
f : float
";

%feature("docstring") set_gaussian_surface_chain_colour_mode "
set the chain colour mode for Gaussian surfaces mode = 1 means each chain has its own colour mode = 2 means the chain colour is determined from NCS/molecular symmetry (so that, in this mode, chains with the same sequence have the same colour

Parameters
----------
mode : short int
";

%feature("docstring") make_acedrg_dictionary_via_CCD_dictionary "

Parameters
----------
imol : int
spec : residue_spec
";

%feature("docstring") make_link "
make a link between the specified atoms

Parameters
----------
imol : int
spec_1 : atom_spec
spec_2 : atom_spec
link_name : str
length : float
";

%feature("docstring") make_link_scm "

Parameters
----------
imol : int
spec_1 : SCM
spec_2 : SCM
link_name : str
length : float
";

%feature("docstring") link_info_scm "

Parameters
----------
imol : int
";

%feature("docstring") make_link_py "

Parameters
----------
imol : int
spec_1 : object
spec_2 : object
link_name : str
length : float
";

%feature("docstring") link_info_py "

Parameters
----------
imol : int
";

%feature("docstring") handle_drag_and_drop_string "
handle the string that get when a file or URL is dropped.

Parameters
----------
uri : str
";

%feature("docstring") undisplay_all_maps_except "
undisplay all maps except the given one

Parameters
----------
imol_map : int
";

%feature("docstring") map_contours "
return a list of pairs of vertices for the lines

Parameters
----------
imol : int
contour_level : float
";

%feature("docstring") map_contours_as_triangles "
return two lists: a list of vertices and a list of index-triples for connection

Parameters
----------
imol : int
contour_level : float
";

%feature("docstring") set_radial_map_colouring_enabled "
enable radial map colouring

Parameters
----------
imol : int
state : int
";

%feature("docstring") set_radial_map_colouring_centre "
radial map colouring centre

Parameters
----------
imol : int
x : float
y : float
z : float
";

%feature("docstring") set_radial_map_colouring_min_radius "
radial map colouring min

Parameters
----------
imol : int
r : float
";

%feature("docstring") set_radial_map_colouring_max_radius "
radial map colouring max

Parameters
----------
imol : int
r : float
";

%feature("docstring") set_radial_map_colouring_invert "
radial map colouring inverted colour map

Parameters
----------
imol : int
invert_state : int
";

%feature("docstring") set_radial_map_colouring_saturation "
radial map colouring saturation

saturation is a number between 0 and 1, typically 0.5

Parameters
----------
imol : int
saturation : float
";

%feature("docstring") set_map_correlation_atom_radius "
The atom radius is not passed as a parameter to correlation.

Parameters
----------
r : float
";

%feature("docstring") map_to_model_correlation_scm "
atom-mask-mode is as follows:

Parameters
----------
imol : int
residue_specs : SCM
neighb_residue_specs : SCM
atom_mask_mode : unsigned short int
imol_map : int
";

%feature("docstring") map_to_model_correlation_stats_scm "
Map-to-model correlation statistics (Guile interface)

:param imol: Model molecule number 
:param residue_specs: Scheme list of residue specs 
:param neighb_residue_specs: Scheme list of neighboring residue specs 
:param atom_mask_mode: Controls which atoms to include 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : SCM
neighb_residue_specs : SCM
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
SCM
    SCM - Association list with statistics
";

%feature("docstring") map_to_model_correlation_py "
Calculate map-to-model correlation (Python interface)

Python wrapper for map_to_model_correlation. Evaluates the fit of specific residues to the electron density map.

:param imol: Model molecule number 
:param residue_specs: Python list of residue specs [[chain_id, resno, ins_code], ...] 
:param neighb_residue_specs: Python list of neighboring residue specs to exclude 
:param atom_mask_mode: Controls which atoms to include (see atom_mask_mode values above) 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : object
neighb_residue_specs : object
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
object
    PyObject* - correlation coefficient as a Python float
";

%feature("docstring") map_to_model_correlation_stats_py "
Get map-to-model correlation statistics (Python interface)

Returns detailed statistics about the correlation between model and map, including mean, standard deviation, and range.

:param imol: Model molecule number 
:param residue_specs: Python list of residue specs 
:param neighb_residue_specs: Python list of neighboring residue specs 
:param atom_mask_mode: Controls which atoms to include 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : object
neighb_residue_specs : object
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
object
    PyObject* - Dictionary with statistics:
";

%feature("docstring") map_to_model_correlation_stats_per_residue_range_py "
Get density statistics per residue range (Python interface)

This is the main function to use when asked \"Which side chain is worst fitting to density?\" It analyzes correlation statistics for all residues in a chain and returns comprehensive data for both all-atom and side-chain-only analysis.

:param imol: Model molecule number 
:param chain_id: Chain identifier (e.g., \"A\", \"B\") 
:param imol_map: Map molecule number 
:param n_residue_per_residue_range: Number of residues per analysis window:
:param exclude_NOC_flag: Whether to exclude backbone N, O, C atoms:

Example usage - Compare main-chain vs side-chain fit:

Parameters
----------
imol : int
chain_id : str
imol_map : int
n_residue_per_residue_range : int
exclude_NOC_flag : short int

Returns
-------
object
    PyObject* - Tuple of two dictionaries (all_atom_stats, sidechain_stats): Each dictionary maps residue_spec to correlation_stats containing:
";

%feature("docstring") map_to_model_correlation "
Calculate the correlation between a map and model for specific residues.

This function calculates the map-to-model correlation for specified residues, excluding grid points that overlap with neighboring residues.

:param imol: Model molecule number 
:param residue_specs: Vector of residue specifications to evaluate 
:param neigh_residue_specs: Vector of neighboring residues whose grid points should be excluded 
:param atom_mask_mode: Controls which atoms are included in the calculation:
:param imol_map: Map molecule number to correlate against

atom-mask-mode is as follows:

Parameters
----------
imol : int
residue_specs : const std::vector< coot::residue_spec_t > &
neigh_residue_specs : const std::vector< coot::residue_spec_t > &
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
float
    Correlation coefficient (float) between model and map
";

%feature("docstring") map_to_model_correlation_stats "
Get detailed statistics for map-to-model correlation.

Returns comprehensive statistics including mean, standard deviation, minimum, and maximum correlation values for the specified residues.

:param imol: Model molecule number 
:param residue_specs: Vector of residue specifications to evaluate 
:param neigh_residue_specs: Vector of neighboring residues to exclude from grid 
:param atom_mask_mode: Controls which atoms are included (see atom_mask_mode values) 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : const std::vector< coot::residue_spec_t > &
neigh_residue_specs : const std::vector< coot::residue_spec_t > &
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
coot::util::density_correlation_stats_info_t
    coot::util::density_correlation_stats_info_t containing:
";

%feature("docstring") map_to_model_correlation_per_residue "
Get map-to-model correlation per residue.

Returns individual correlation values for each specified residue. Useful for identifying which specific residues fit poorly.

:param imol: Model molecule number 
:param specs: Vector of residue specifications 
:param atom_mask_mode: Controls which atoms to include 
:param imol_map: Map molecule number

Parameters
----------
imol : int
specs : const std::vector< coot::residue_spec_t > &
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
std::vector< std::pair< coot::residue_spec_t, float > >
    Vector of pairs: (residue_spec, correlation_value)
";

%feature("docstring") map_to_model_correlation_stats_per_residue "
Get detailed density statistics per residue.

Returns comprehensive density statistics for each residue including correlation, mean, standard deviation, and other metrics.

:param imol: Model molecule number 
:param residue_specs: Vector of residue specifications 
:param atom_mask_mode: Controls which atoms to include 
:param atom_radius_for_masking: Radius around atoms for masking (typically 1.5 Å) 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : const std::vector< coot::residue_spec_t > &
atom_mask_mode : unsigned short int
atom_radius_for_masking : float
imol_map : int

Returns
-------
std::map< coot::residue_spec_t, coot::util::density_stats_info_t >
    Map of residue_spec to density_stats_info_t containing detailed statistics
";

%feature("docstring") map_to_model_correlation_stats_per_residue_range "
Get density statistics per residue range.

Analyzes correlation statistics for residue ranges (windows) along a chain. The middle residue of each range represents the statistics for that window.

:param imol: Model molecule number 
:param chain_id: Chain identifier (e.g., \"A\", \"B\") 
:param imol_map: Map molecule number 
:param n_residue_per_residue_range: Number of residues per analysis window (typically 1 for per-residue) 
:param exclude_NOC_flag: Whether to exclude backbone N, O, C atoms (1=yes, 0=no)

Parameters
----------
imol : int
chain_id : str
imol_map : int
n_residue_per_residue_range : int
exclude_NOC_flag : short int

Returns
-------
std::pair< std::map< coot::residue_spec_t, coot::util::density_correlation_stats_info_t >, std::map< coot::residue_spec_t, coot::util::density_correlation_stats_info_t > >
    Pair of maps:
";

%feature("docstring") map_to_model_correlation_per_residue_scm "
Map-to-model correlation per residue (Guile interface)

:param imol: Model molecule number 
:param residue_specs: Scheme list of residue specs 
:param atom_mask_mode: Controls which atoms to include 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : SCM
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
SCM
    SCM - List of pairs: ((residue-spec correlation) ...)
";

%feature("docstring") map_to_model_correlation_stats_per_residue_scm "
Map-to-model correlation stats per residue (Guile interface)

:param imol: Model molecule number 
:param residue_specs_scm: Scheme list of residue specs 
:param atom_mask_mode: Controls which atoms to include 
:param atom_radius_for_masking: Radius for atom masking 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs_scm : SCM
atom_mask_mode : unsigned short int
atom_radius_for_masking : float
imol_map : int

Returns
-------
SCM
    SCM - Association list mapping residue specs to stats
";

%feature("docstring") map_to_model_correlation_stats_per_residue_range_scm "

Parameters
----------
imol : int
chain_id : str
imol_map : int
n_residue_per_residue_range : int
exclude_NOC_flag : short int
";

%feature("docstring") qq_plot_map_and_model_scm "
QQ plot of the model density correlation, reported per residue.

atom-mask-mode is as follows:

Parameters
----------
imol : int
residue_specs_scm : SCM
neigh_residue_specs_scm : SCM
atom_mask_mode : unsigned short int
imol_map : int
";

%feature("docstring") map_to_model_correlation_per_residue_py "
Get map-to-model correlation per residue (Python interface)

Returns correlation values individually for each specified residue. Essential for identifying which specific residues have poor density fit.

:param imol: Model molecule number 
:param residue_specs: Python list of residue specs 
:param atom_mask_mode: Controls which atoms to include 
:param imol_map: Map molecule number

Parameters
----------
imol : int
residue_specs : object
atom_mask_mode : unsigned short int
imol_map : int

Returns
-------
object
    PyObject* - List of tuples: [(residue_spec, correlation), ...]
";

%feature("docstring") qq_plot_map_and_model_py "

Parameters
----------
imol : int
residue_specs_py : object
neigh_residue_specs_py : object
atom_mask_mode : unsigned short int
imol_map : int
";

%feature("docstring") density_score_residue_scm "

Parameters
----------
imol : int
residue_spec : SCM
imol_map : int
";

%feature("docstring") density_score_residue_py "

Parameters
----------
imol : int
residue_spec : object
imol_map : int
";

%feature("docstring") density_score_residue "
simple density score for given residue (over-ridden by scripting function)

Parameters
----------
imol : int
chain_id : const char *
res_no : int
ins_code : const char *
imol_map : int
";

%feature("docstring") map_mean_scm "
return sigma for the given map. Return scheme False if not a valid map molecule number.

Parameters
----------
imol : int
";

%feature("docstring") map_sigma_scm "

Parameters
----------
imol : int
";

%feature("docstring") map_statistics_scm "
return either scheme false on non-a-map or list (mean, standard-deviation, skew, kurtosis)

Parameters
----------
imol : int
";

%feature("docstring") map_mean_py "
return sigma for the given map. Return Python False if not a valid map molecule number.

Parameters
----------
imol : int
";

%feature("docstring") map_sigma_py "

Parameters
----------
imol : int
";

%feature("docstring") map_statistics_py "

Parameters
----------
imol : int
";

%feature("docstring") get_sequence_as_fasta_for_chain "
get the sequence for chain_id in imol

Parameters
----------
imol : int
chain_id : str
";

%feature("docstring") write_sequence "
write the sequence for imol as fasta

Parameters
----------
imol : int
file_name : str
";

%feature("docstring") res_tracer "
trace the given map and try to apply the sequence in the given pir file

Parameters
----------
imol_map : int
pir_file_name : str
";

%feature("docstring") register_interesting_positions_list_scm "

Parameters
----------
pos_list : SCM
";

%feature("docstring") register_interesting_positions_list_py "

Parameters
----------
pos_list : object
";

%feature("docstring") molecule_atom_overlaps_py "

Parameters
----------
imol : int
";

%feature("docstring") molecule_atom_overlaps_scm "

Parameters
----------
imol : int
";

%feature("docstring") prodrg_import_function "
import given mdl file into prodrg or other 3d generation program

the function passed to lbg, so that it calls it when a new prodrg-in.mdl file has been made. We no longer have a timeout function waiting for prodrg-in.mdl to be updated/written.

Parameters
----------
file_name : str
comp_id : str
";

%feature("docstring") sbase_import_function "
import molecule from CCP4 SRS (or SBase, as it used to be called).

the function passed to lbg, so that it calls it when a new SBase comp_id is required. We no longer have a timeout function waiting for prodrg-in.mdl to be updated/written.

Parameters
----------
comp_id : str
";

%feature("docstring") align_to_closest_chain "
align sequence to closest chain (compare across all chains in all molecules).

Typically match_fraction is 0.95 or so.

Return the molecule number and chain id if successful, return -1 as the molecule number if not.

Parameters
----------
target_seq : str
match_fraction : float
";

%feature("docstring") align_to_closest_chain_py "

Parameters
----------
target_seq : str
match_fraction : float
";

%feature("docstring") align_to_closest_chain_scm "

Parameters
----------
target_seq : str
match_fraction : float
";

%feature("docstring") spherical_density_overlap "

Parameters
----------
i_scm : SCM
j_scm : SCM
";

%feature("docstring") resolve_clashing_sidechains_by_deletion "

Parameters
----------
imol : int
";

%feature("docstring") resolve_clashing_sidechains_by_rebuilding "

Parameters
----------
imol : int
";

%feature("docstring") simple_text_dialog "
make a simple text dialog.

Parameters
----------
dialog_title : str
text : str
geom_x : int
geom_y : int
";

%feature("docstring") graphics_to_phenix_geo_representation "
phenix GEO bonds representation

Parameters
----------
imol : int
mode : int
g : const coot::phenix_geo_bonds &
";

%feature("docstring") graphics_to_phenix_geo_representation "
phenix GEO bonds representation, read from file

Parameters
----------
imol : int
mode : int
geo_file_name : str
";

%feature("docstring") set_python_draw_function "
client/server functions

Parameters
----------
command_string : str
";

%feature("docstring") pathology_data "

Parameters
----------
mtz_file_name : str
fp_col : str
sigfp_col : str
";

%feature("docstring") encode_ints "
encoding of ints

Parameters
----------
i1 : int
i2 : int
";

%feature("docstring") decode_ints "

Parameters
----------
i : int
";

%feature("docstring") store_keyed_user_name "
store username and password for the database.

Parameters
----------
key : str
user_name : str
passwd : str
";

%feature("docstring") scm_to_residue_specs "

Parameters
----------
s : SCM
";

%feature("docstring") key_sym_code_scm "

Parameters
----------
s_scm : SCM
";

%feature("docstring") py_to_residue_specs "

Parameters
----------
s : object
";

%feature("docstring") key_sym_code_py "

Parameters
----------
po : object
";

%feature("docstring") scm_to_py "

Parameters
----------
s : SCM
";

%feature("docstring") py_to_scm "

Parameters
----------
o : object
";

%feature("docstring") scm_symop_strings_to_space_group "

Parameters
----------
symop_string_list : SCM
";

%feature("docstring") py_symop_strings_to_space_group "

Parameters
----------
symop_string_list : object
";

%feature("docstring") set_use_sounds "
enable or diable sounds (coot needs to have been compiled with sounds of course)

Parameters
----------
state : bool
";

%feature("docstring") curmudgeon_mode "
no sounds
";

%feature("docstring") halloween "
easter egg 2023
";

%feature("docstring") display_svg_from_file_in_a_dialog "

Parameters
----------
file_name : str
";

%feature("docstring") display_svg_from_string_in_a_dialog "

Parameters
----------
string : str
title : str
";

%feature("docstring") display_pae_from_file_in_a_dialog "

Parameters
----------
imol : int
file_name : str
";

%feature("docstring") read_interesting_places_json_file "

Parameters
----------
file_name : str
";

%feature("docstring") setup_tomo_slider "
return the section index (the middle section currently)

Parameters
----------
imol : int
";

%feature("docstring") tomo_section_view "

Parameters
----------
imol : int
axis_id : int
";

%feature("docstring") set_tomo_section_view_section "

Parameters
----------
imol : int
section_index : int
";

%feature("docstring") set_tomo_picker_mode_is_active "
set tomo picker is active

Parameters
----------
state : short int
";

%feature("docstring") tomo_map_analysis "

Parameters
----------
imol_map : int
spot_positions : object
";

%feature("docstring") tomo_map_analysis_2 "

Parameters
----------
imol_map : int
spot_positions : object
";

%feature("docstring") reverse_map "
negative becomes positive and positive becomes negative. Apply an offset so that most of the map is above zero.

Parameters
----------
imol_map : int
";

%feature("docstring") read_positron_metadata "

Parameters
----------
z_data : str
table : str
";

%feature("docstring") positron_pathway "

Parameters
----------
map_molecule_list_py : object
pathway_points_py : object
";

%feature("docstring") positron_plot_py "

Parameters
----------
fn_z_csv : str
fn_s_csv : str
base_map_index_list : object
";

%feature("docstring") global_phasing_screen "

Parameters
----------
imol : int
screen_dict : object
";

%feature("docstring") positron_plot_internal "

Parameters
----------
fn_z_csv : str
fn_s_csv : str
base_map_index_list : const std::vector< int > &
";

%feature("docstring") filtered_by_glob "

Parameters
----------
pre_directory : str
data_type : int
";

%feature("docstring") string_member "

Parameters
----------
search : str
list : list
";

%feature("docstring") compare_strings "

Parameters
----------
a : str
b : str
";

%feature("docstring") add_cablam_markup "

Parameters
----------
imol : int
cablam_file_name : str
";

%feature("docstring") add_cablam_markup_scm "

Parameters
----------
imol : int
cablam_log_file_name : str
";

%feature("docstring") add_cablam_markup_py "

Parameters
----------
imol : int
cablam_log_file_name : str
";

%feature("docstring") set_rotation_centre "

Parameters
----------
pos : const clipper::Coord_orth &
";

%feature("docstring") goto_next_atom_maybe_scm "

Parameters
----------
chain_id : const char *
resno : int
ins_code : const char *
atom_name : const char *
";

%feature("docstring") goto_prev_atom_maybe_scm "

Parameters
----------
chain_id : const char *
resno : int
ins_code : const char *
atom_name : const char *
";

%feature("docstring") goto_next_atom_maybe_py "

Parameters
----------
chain_id : const char *
resno : int
ins_code : const char *
atom_name : const char *
";

%feature("docstring") goto_prev_atom_maybe_py "

Parameters
----------
chain_id : const char *
resno : int
ins_code : const char *
atom_name : const char *
";

%feature("docstring") set_go_to_atom_from_spec "

Parameters
----------
atom_spec : atom_spec
";

%feature("docstring") set_go_to_atom_from_res_spec "

Parameters
----------
spec : residue_spec
";

%feature("docstring") set_go_to_atom_from_res_spec_scm "

Parameters
----------
residue_spec : SCM
";

%feature("docstring") set_go_to_atom_from_atom_spec_scm "

Parameters
----------
residue_spec : SCM
";

%feature("docstring") set_go_to_atom_from_res_spec_py "

Parameters
----------
residue_spec : object
";

%feature("docstring") set_go_to_atom_from_atom_spec_py "

Parameters
----------
residue_spec : object
";

%feature("docstring") regen_map_internal "
We overwrite the imol_map and we also presume that the grid sampling of the contributing maps match. This makes it much faster to generate than an average map.

Parameters
----------
imol_map : int
weighted_map_indices : const std::vector< std::pair< int, float > > &
";

%feature("docstring") make_weighted_map_simple_internal "

Parameters
----------
weighted_map_indices : const std::vector< std::pair< int, float > > &
";

%feature("docstring") colour_map_by_other_map "

Parameters
----------
imol_map : int
imol_map_used_for_colouring : int
";

%feature("docstring") colour_map_by_other_map_py "
the colour_table should be a list of colours

So, if the map has 4 entries covering the range from 0 to 1, then the table_bin_size would be 0.25 and the colour_table list would have 4 entries covering the range 0->0.25, 0.25->0.5, 0.5->0.75, 0.75->1.0

Parameters
----------
imol_map : int
imol_map_used_for_colouring : int
table_bin_start : float
table_bin_size : float
colour_table_list : object
";

%feature("docstring") export_molecule_as_x3d "

Parameters
----------
imol : int
";

%feature("docstring") export_molecule_as_obj "

Parameters
----------
imol : int
file_name : str
";

%feature("docstring") export_molecule_as_gltf "

Parameters
----------
imol : int
file_name : str
";

%feature("docstring") colour_map_by_other_map_turn_off "
turn of colour map by other map

Parameters
----------
imol_map : int
";

%feature("docstring") add_density_map_cap "
Add map caps.
";

%feature("docstring") recolour_mesh_by_map "
colour meshes (e.g. Ribbon diagrams) by map

scale might be 2 and offset 1 (for example)

Parameters
----------
imol_model : int
imol_map : int
scale : float
offset : float
";

%feature("docstring") import_bild "

Parameters
----------
file_name : str
";

%feature("docstring") servalcat_fofc "

Parameters
----------
imol_model : int
imol_fofc_map : int
half_map_1 : str
half_map_2 : str
resolution : float
";

%feature("docstring") servalcat_refine "
resolution in A.

Parameters
----------
imol_model : int
half_map_1 : str
half_map_2 : str
mask_map : str
resolution : float
";

%feature("docstring") run_acedrg_link_generation "
run acedrg link

Parameters
----------
acedrg_link_command : str
";

%feature("docstring") add_toolbar_subprocess_button "
run generic process - doesn't work at the moment - on_completion_args is wrongly interpretted.

Parameters
----------
button_label : str
subprocess_command : str
arg_list : object
on_completion_function : object
on_completion_args : object
";

%feature("docstring") compare_mtimes "

Parameters
----------
a : None
b : None
";

%feature("docstring") parse_ccp4i_defs "

Parameters
----------
filename : str
";

%feature("docstring") ccp4_project_directory "

Parameters
----------
ccp4_project_name : str
";

%feature("docstring") add_to_history "

Parameters
----------
ls : list
";

%feature("docstring") add_to_history_simple "

Parameters
----------
cmd : str
";

%feature("docstring") add_to_history_typed "

Parameters
----------
command : str
args : const std::vector< coot::command_arg_t > &
";

%feature("docstring") single_quote "

Parameters
----------
s : str
";

%feature("docstring") pythonize_command_name "

Parameters
----------
s : str
";

%feature("docstring") schemize_command_name "

Parameters
----------
s : str
";

%feature("docstring") languagize_command "

Parameters
----------
command_parts : list
";

%feature("docstring") add_to_database "

Parameters
----------
command_strings : list
";

%feature("docstring") merge_molecules_by_vector "

Parameters
----------
add_molecules : const std::vector< int > &
imol : int
";

%feature("docstring") list_nomenclature_errors "

Parameters
----------
imol : int
";

%feature("docstring") list_nomenclature_errors_scm "

Parameters
----------
imol : int
";

%feature("docstring") list_nomenclature_errors_py "

Parameters
----------
imol : int
";

%feature("docstring") show_fix_nomenclature_errors_gui "

Parameters
----------
imol : int
nomenclature_errors : const std::vector< std::pair< std::string, coot::residue_spec_t > > &
";

%feature("docstring") dipole_to_scm "

Parameters
----------
dp : std::pair< coot::dipole, int >
";

%feature("docstring") dipole_to_py "

Parameters
----------
dp : std::pair< coot::dipole, int >
";

%feature("docstring") run_scheme_command "

Parameters
----------
scheme_command : const char *
";

%feature("docstring") run_python_command "

Parameters
----------
python_command : const char *
";

%feature("docstring") pyrun_simple_string "

Parameters
----------
python_command : const char *
";

%feature("docstring") residue_spec_to_scm "

Parameters
----------
res : residue_spec
";

%feature("docstring") residue_spec_to_py "

Parameters
----------
res : residue_spec
";

%feature("docstring") residue_spec_make_triple_py "

Parameters
----------
residue_spec_py : object
";

%feature("docstring") residue_spec_from_scm "

Parameters
----------
residue_in : SCM
";

%feature("docstring") residue_spec_from_py "

Parameters
----------
residue_in : object
";

%feature("docstring") get_residue_by_type "

Parameters
----------
imol : int
residue_type : str
";

%feature("docstring") get_residue_specs_in_mol "

Parameters
----------
imol : int
residue_type : str
";

%feature("docstring") get_residue_specs_in_mol_py "

Parameters
----------
imol : int
residue_type : str
";

%feature("docstring") get_residue_by_type_scm "

Parameters
----------
 : int
residue_type : str
";

%feature("docstring") get_residue_by_type_py "

Parameters
----------
 : int
residue_type : str
";

%feature("docstring") rigid_body_fit_with_residue_ranges "
return 0 on fail to refine (no sensible place to put atoms) and 1 on fitting happened.

Parameters
----------
imol : int
ranges : const std::vector< coot::high_res_residue_range_t > &
";

%feature("docstring") morph_fit_all "

Parameters
----------
imol : int
transformation_averaging_radius : float
";

%feature("docstring") morph_fit_chain "
Morph the given chain.

Parameters
----------
imol : int
chain_id : str
transformation_averaging_radius : float
";

%feature("docstring") morph_fit_residues_scm "

Parameters
----------
imol : int
residue_specs : SCM
transformation_averaging_radius : float
";

%feature("docstring") morph_fit_residues_py "

Parameters
----------
imol : int
residue_specs : object
transformation_averaging_radius : float
";

%feature("docstring") morph_fit_residues "
morph the given residues.

Parameters
----------
imol : int
residue_specs : const std::vector< coot::residue_spec_t > &
transformation_averaging_radius : float
";

%feature("docstring") morph_fit_by_secondary_structure_elements "
morph transformation are based primarily on rigid body refinement of the secondary structure elements.

Parameters
----------
imol : int
chain_id : str
";

%feature("docstring") check_waters_baddies "

Parameters
----------
imol : int
b_factor_lim : float
map_sigma_lim : float
min_dist : float
max_dist : float
part_occ_contact_flag : short int
zero_occ_flag : short int
logical_operator_and_or_flag : short int
";

%feature("docstring") find_blobs "

Parameters
----------
imol_model : int
imol_map : int
cut_off_density_level : float
";

%feature("docstring") find_blobs_scm "
find blobs

Parameters
----------
imol_model : int
imol_map : int
cut_off_density_level : float
";

%feature("docstring") find_blobs_py "

Parameters
----------
imol_model : int
imol_map : int
cut_off_density_level : float
";

%feature("docstring") b_factor_distribution_graph "
B-factor distribution histogram.

Parameters
----------
imol : int
";

%feature("docstring") monomer_lib_3_letter_codes_matching "

Parameters
----------
search_string : str
allow_minimal_descriptions_flag : short int
";

%feature("docstring") mutate_residue_range "

Parameters
----------
imol : int
chain_id : str
res_no_start : int
res_no_end : int
target_sequence : str
";

%feature("docstring") mutate_internal "

Parameters
----------
ires : int
chain_id : const char *
imol : int
target_res_type : str
";

%feature("docstring") mutate_active_residue_to_single_letter_code "
mutate active residue to single letter code slc

Parameters
----------
slc : str
";

%feature("docstring") show_keyboard_mutate_frame "
show keyboard mutate frame
";

%feature("docstring") mutate_by_overlap "
mutate by overlap

Parameters
----------
imol : int
chain_id : str
res_no : int
new_type : str
";

%feature("docstring") overlap_ligands_internal "

Parameters
----------
imol_ligand : int
imol_ref : int
chain_id_ref : const char *
resno_ref : int
apply_rtop_flag : bool
";

%feature("docstring") do_smiles_to_simple_3d_overlay_frame "
display the SMILES entry. This is the simple version - no dictionary is generated.
";

%feature("docstring") get_residues_in_chain_py "

Parameters
----------
imol : int
chain_id : str

Returns
-------
object
    a python list of residue specs for the residues in the given chain
";

%feature("docstring") add_animated_ligand_interaction "

Parameters
----------
imol : int
lb : const pli::fle_ligand_bond_t &
";

%feature("docstring") cootaneer_internal "

Parameters
----------
imol_map : int
imol_model : int
atom_spec : atom_spec
";

%feature("docstring") is_interesting_dots_object_next_p "

Parameters
----------
vs : list
";

%feature("docstring") generic_string_vector_to_list_internal "

Parameters
----------
v : list
";

%feature("docstring") generic_int_vector_to_list_internal "

Parameters
----------
v : const std::vector< int > &
";

%feature("docstring") generic_list_to_string_vector_internal "

Parameters
----------
l : SCM
";

%feature("docstring") rtop_to_scm "

Parameters
----------
rtop : const clipper::RTop_orth &
";

%feature("docstring") inverse_rtop_scm "

Parameters
----------
rtop_scm : SCM
";

%feature("docstring") atom_spec_from_scm_expression "

Parameters
----------
expr : SCM
";

%feature("docstring") atom_spec_to_scm "

Parameters
----------
spec : atom_spec
";

%feature("docstring") generic_string_vector_to_list_internal_py "

Parameters
----------
v : list
";

%feature("docstring") generic_int_vector_to_list_internal_py "

Parameters
----------
v : const std::vector< int > &
";

%feature("docstring") generic_list_to_string_vector_internal_py "

Parameters
----------
l : object
";

%feature("docstring") rtop_to_python "

Parameters
----------
rtop : const clipper::RTop_orth &
";

%feature("docstring") inverse_rtop_py "

Parameters
----------
rtop_py : object
";

%feature("docstring") atom_spec_from_python_expression "

Parameters
----------
expr : object
";

%feature("docstring") atom_spec_to_py "

Parameters
----------
spec : atom_spec
";

%feature("docstring") set_display_control_button_state "

Parameters
----------
imol : int
button_type : str
state : int
";

%feature("docstring") set_use_trackpad "
Use left-mouse for view rotation.

Parameters
----------
state : short int
";

%feature("docstring") set_use_primary_mouse_button_for_view_rotation "
this is an alias for the above

Parameters
----------
state : short int
";

%feature("docstring") get_coords_for_accession_code "
if possible, read in the new coords getting coords via web.

(no return value because get-url-str does not return one).

Parameters
----------
code : str
";

%feature("docstring") coot_get_url_as_string_internal "

Parameters
----------
url : const char *
";

%feature("docstring") stop_curl_download "

Parameters
----------
file_name : const char *
";

%feature("docstring") get_drug_mdl_via_wikipedia_and_drugbank "

Parameters
----------
drugname : str
";

%feature("docstring") fetch_and_superpose_alphafold_models "
fetch and superpose AlphaFold models corresponding to model

model must have Uniprot DBREF info in the header.

Parameters
----------
imol : int
";

%feature("docstring") fetch_alphafold_model_for_uniprot_id "
return the model number

Parameters
----------
uniprot_id : str
";

%feature("docstring") fetch_emdb_map "
Loads up map frmo emdb.

Parameters
----------
emd_accession_code : str
";

%feature("docstring") fetch_cod_entry "
return the COD entry, return a molecule index

Parameters
----------
cod_entry_id : str
";

%feature("docstring") orient_view "

Parameters
----------
imol : int
central_residue_spec : residue_spec
neighbour_residue_spec : residue_spec
";

%feature("docstring") topological_equivalence_chiral_centres "

Parameters
----------
residue_type : str
";

%feature("docstring") screendump_tga "

Parameters
----------
file_name : str
";

%feature("docstring") set_framebuffer_scale_factor "

Parameters
----------
sf : int
";

%feature("docstring") set_use_perspective_projection "
set use perspective mode

Parameters
----------
state : short int
";

%feature("docstring") use_perspective_projection_state "
query if perspective mode is being used
";

%feature("docstring") set_perspective_fov "
set the perspective fov. Default 20 degrees.

Parameters
----------
degrees : float
";

%feature("docstring") set_use_ambient_occlusion "
set use ambient occlusion

Parameters
----------
state : short int
";

%feature("docstring") use_ambient_occlusion_state "
query use ambient occlusion
";

%feature("docstring") set_use_depth_blur "
set use depth blur

Parameters
----------
state : short int
";

%feature("docstring") use_depth_blur_state "
query use depth blur
";

%feature("docstring") set_use_fog "
set use fog

Parameters
----------
state : short int
";

%feature("docstring") use_fog_state "
query use fog
";

%feature("docstring") set_use_outline "
set use ourline

Parameters
----------
state : short int
";

%feature("docstring") use_outline_state "
query use outline
";

%feature("docstring") set_map_shininess "
set the map shininess

Parameters
----------
imol : int
shininess : float
";

%feature("docstring") set_map_specular_strength "
set the map specular strength

Parameters
----------
imol : int
specular_strength : float
";

%feature("docstring") set_draw_normals "

Parameters
----------
state : short int
";

%feature("docstring") set_draw_mesh "

Parameters
----------
imol : int
mesh_index : int
state : short int
";

%feature("docstring") draw_mesh_state "
return -1 on unable to lookup mesh

Parameters
----------
imol : int
mesh_index : int
";

%feature("docstring") set_map_material_specular "

Parameters
----------
imol : int
specular_strength : float
shininess : float
";

%feature("docstring") set_model_material_specular "

Parameters
----------
imol : int
specular_strength : float
shininess : float
";

%feature("docstring") set_model_material_ambient "
set the ambient

Parameters
----------
imol : int
r : float
g : float
b : float
alpha : float
";

%feature("docstring") set_model_material_diffuse "

Parameters
----------
imol : int
r : float
g : float
b : float
alpha : float
";

%feature("docstring") set_model_goodselliness "
set the goodselliness (pastelization_factor) 0.3 is about right, but \"the right value\" depends on the renderer, may be some personal choice.

Parameters
----------
pastelization_factor : float
";

%feature("docstring") set_map_fresnel_settings "

Parameters
----------
imol : int
state : short int
bias : float
scale : float
power : float
";

%feature("docstring") set_atom_radius_scale_factor "

Parameters
----------
imol : int
scale_factor : float
";

%feature("docstring") set_use_fancy_lighting "
set use fancy lighting (default 1 = true);

Parameters
----------
state : short int
";

%feature("docstring") set_use_simple_lines_for_model_molecules "
set use simple lines for model molecule

Parameters
----------
state : short int
";

%feature("docstring") set_fresnel_colour "

Parameters
----------
imol : int
red : float
green : float
blue : float
opacity : float
";

%feature("docstring") set_focus_blur_z_depth "

Parameters
----------
z : float
";

%feature("docstring") set_focus_blur_strength "
set focus blur strength

Parameters
----------
st : float
";

%feature("docstring") set_shadow_strength "
set shadow stren

Parameters
----------
s : float
";

%feature("docstring") set_shadow_resolution "
set the shadow resolution (1,2,3,4)

Parameters
----------
reso_multiplier : int
";

%feature("docstring") set_shadow_box_size "
set shadow box size - default 66;

Parameters
----------
size : float
";

%feature("docstring") set_ssao_kernel_n_samples "
set SSAO kernel n samples

Parameters
----------
n_samples : int
";

%feature("docstring") set_ssao_strength "
set SSAO strength

Parameters
----------
strength : float
";

%feature("docstring") set_ssao_radius "
set SSAO strength

Parameters
----------
radius : float
";

%feature("docstring") set_ssao_bias "
set SSAO bias

Parameters
----------
bias : float
";

%feature("docstring") set_ssao_blur_size "
set SSAO blur size (0, 1, or 2)

Parameters
----------
blur_size : int
";

%feature("docstring") set_shadow_softness "
set the shadow softness (1, 2 or 3)

Parameters
----------
softness : int
";

%feature("docstring") set_shadow_texture_resolution_multiplier "
set the shadow softness (1, 2 or 3)

Parameters
----------
m : int
";

%feature("docstring") set_effects_shader_output_type "
adjust the effects shader output type (for debugging effects)

Parameters
----------
type : int
";

%feature("docstring") set_effects_shader_brightness "
adjust the effects shader brightness

Parameters
----------
f : float
";

%feature("docstring") set_effects_shader_gamma "
adjust the effects shader gamma

Parameters
----------
f : float
";

%feature("docstring") set_bond_smoothness_factor "
set bond smoothness (default 1 (not smooth))

Parameters
----------
fac : int
";

%feature("docstring") set_draw_gl_ramachandran_plot_during_refinement "
set the draw state of the Ramachandran plot display during Real Space Refinement

Parameters
----------
state : short int
";

%feature("docstring") set_fps_timing_scale_factor "
set the FPS timing scale factor - default 0.0025

Parameters
----------
f : float
";

%feature("docstring") set_draw_background_image "
draw background image

Parameters
----------
state : bool
";

%feature("docstring") load_gltf_model "
load a gltf model

If the gltf files does not exist, an empty model will be created

:param gltf_file_name: is the name of the gltf file to load

Parameters
----------
gltf_file_name : str

Returns
-------
int
    the model index of the loaded model.
";

%feature("docstring") set_model_animation_parameters "
set the model animation parameters

Parameters
----------
model_index : int
amplitude : float
wave_numer : float
freq : float
";

%feature("docstring") set_model_animation_state "
enable/disable the model animation (on or off)

Parameters
----------
model_index : int
state : bool
";

%feature("docstring") scale_model "
load a gltf model

Parameters
----------
model_index : int
scale_factor : float
";

%feature("docstring") reset_framebuffers "
reset the frame buffers
";

