/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") M2T_updateFloatParameter "
Update float parameter for MoleculesToTriangles molecular mesh.

Parameters
----------
imol : int
param_name : str
value : float
";

%feature("docstring") M2T_updateIntParameter "
Update int parameter for MoleculesToTriangles molecular mesh.

Parameters
----------
imol : int
param_name : str
value : int
";

