/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") sequence_comparison_to_chains "

Parameters
----------
imol : int
sequence : str
";

%feature("docstring") assign_sequence_to_best_matching_chain "

Parameters
----------
sequence : str
";

%feature("docstring") assign_sequences_to_best_matching_chain_from_fasta "

Parameters
----------
fasta_file_name : str
";

%feature("docstring") apply_fasta_multi_to_fragment "

Parameters
----------
imol : int
chain_id : str
resno_start : int
resno_end : int
imol_map : int
fam : const coot::fasta_multi &
";

