/* Auto-generated SWIG docstrings from Doxygen XML */
/* Generated by xml-to-swig-docstrings.py */

%feature("docstring") add_molecular_representation_py "
add a molecular representation, e.g. Ribbon diagram or surface

e.g. 0, \"//C\", \"RampChainsScheme\", \"Ribbon\"

  imol  the molecule index   atom_selection_py  the atom-selection in mmdb-style CID   ColorScheme_py  colour-scheme-name, e.g. \"colorRampChainsScheme\" or \"Chain\" or \"colorBySecondaryScheme\"   style_py  the representation style, e.g. \"Ribbon\" or \"MolecularSurface\" -1 on failure, the representation index on success

Parameters
----------
imol : int
    the molecule index
atom_selection_py : object
    the atom-selection in mmdb-style CID
ColorScheme_py : object
    colour-scheme-name, e.g. \"colorRampChainsScheme\" or \"Chain\" or \"colorBySecondaryScheme\"
style_py : object
    the representation style, e.g. \"Ribbon\" or \"MolecularSurface\"
";

%feature("docstring") add_molecular_representation_scm "

Parameters
----------
imol : int
atom_selection_scm : SCM
ColorScheme_scm : SCM
style_scm : SCM
";

%feature("docstring") add_ribbon_representation_with_user_defined_colours "
add ribbon representation with user-defined colours

not dependent on scm or python

  imol  the molecule index   name  the name to appear in the display control widget will be -1 - the return value currently has no meaning.

Parameters
----------
imol : int
    the molecule index
name : str
    the name to appear in the display control widget
";

%feature("docstring") remove_molecular_representation "
remove molecular representation

  imol  the molecule index   rep_no  the representation-index

Parameters
----------
imol : int
    the molecule index
rep_no : int
    the representation-index
";

