
echo doxygen...
doxygen coot-dox.cfg > doxygen.log 2>&1
echo conveting from xml to feature docstrings
python3 xml-to-swig-docstrings.py --output       coot_c_interface_docs.i doxygen/xml/c-interface_8h.xml
python3 xml-to-swig-docstrings.py --output      coot_cc_interface_docs.i doxygen/xml/cc-interface_8hh.xml
python3 xml-to-swig-docstrings.py --output     coot_rsr_functions_docs.i doxygen/xml/rsr-functions_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_read_molecule_functions_docs.i doxygen/xml/read-molecule_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_network_functions_docs.i      doxygen/xml/network-get_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_molecular_representation.i  doxygen/xml/cc-interface-molecular-representation_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_user_defined_atom_colours.i doxygen/xml/cc-interface-user-defined-atom-colours_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_refine_docs.i           doxygen/xml/c-interface-refine_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_ligands_swig_docs.i     doxygen/xml/c-interface-ligands-swig_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_generic_objects_docs.i  doxygen/xml/c-interface-generic-objects_8h.xml
python3 xml-to-swig-docstrings.py --output coot_probe_clash_score_docs.i            doxygen/xml/probe-clash-score_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_sdf_interface_docs.i                doxygen/xml/sdf-interface_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_get_monomer_docs.i                  doxygen/xml/get-monomer_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_curlew_docs.i                       doxygen/xml/curlew_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_refmac_docs.i           doxygen/xml/c-interface-refmac_8h.xml
python3 xml-to-swig-docstrings.py --output coot_generic_display_objects_c_docs.i    doxygen/xml/generic-display-objects-c_8h.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_alignment_docs.i       doxygen/xml/cc-interface-alignment_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_graphics.i             doxygen/xml/cc-interface-graphics_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_preferences_docs.i      doxygen/xml/c-interface-preferences_8h.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_scripting_docs.i       doxygen/xml/cc-interface-scripting_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_curl_utils_docs.i                   doxygen/xml/curl-utils_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_pythonic_cfc_docs.i                 doxygen/xml/pythonic-cfc_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_mogul_docs.i            doxygen/xml/c-interface-mogul_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_sequence_docs.i         doxygen/xml/c-interface-sequence_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_validation_docs.i                   doxygen/xml/validation_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cmtz_interface_docs.i               doxygen/xml/cmtz-interface_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_database_docs.i         doxygen/xml/c-interface-database_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_python_docs.i           doxygen/xml/c-interface-python_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_c_interface_refine_c_docs.i         doxygen/xml/c-interface-refine_8h.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_ncs_docs.i             doxygen/xml/cc-interface-ncs_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_nef_docs.i                          doxygen/xml/nef_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_M2T_interface_docs.i                doxygen/xml/M2T-interface_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_lbg_interface_docs.i                doxygen/xml/lbg-interface_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_coot_version_docs.i                 doxygen/xml/coot-version_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_globularize_docs.i                  doxygen/xml/globularize_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_file_system_utils_docs.i            doxygen/xml/file-system-utils_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cfc_2025_docs.i                     doxygen/xml/cfc-2025_8hh.xml
python3 xml-to-swig-docstrings.py --output coot_cc_interface_image_docs.i           doxygen/xml/cc-interface-image_8hh.xml