/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifndef BEGIN_C_DECLS
#ifdef __cplusplus
#define BEGIN_C_DECLS extern "C" {
#define END_C_DECLS }
#else
#define BEGIN_C_DECLS
#define END_C_DECLS
#endif
#endif

BEGIN_C_DECLS

GtkWidget*
seq_lookup_widget (GtkWidget       *widget,
		   const gchar     *widget_name);
GtkWidget* create_sequence_view_dialog (void);
void on_sequence_view_close_button_clicked (GtkButton *button,
					    gpointer         user_data);
void
on_sequence_view_dialog_destroy            (GtkWidget       *widget,
                                            gpointer         user_data);

END_C_DECLS
