#!/bin/sh

rdkit_release="Release_2026_03_3"
graphene_release="1.10.8"
libsigcpp_release="3.8.0"
boost_release="1.91.0-1"
gemmi_release="0.7.0"
maeparser_release="1.3.3"
coordgen_release="3.0.2"
eigen_release="5.0.1"
zlib_release="1.3.2"
