#ifndef API_BOND_COLOUR_HH
#define API_BOND_COLOUR_HH

namespace coot {
   enum class api_bond_colour_t { UNSET_TYPE = -1, NORMAL_BONDS=1, CA_BONDS=2,
      COLOUR_BY_CHAIN_BONDS=3,
      CA_BONDS_PLUS_LIGANDS=4, BONDS_NO_WATERS=5, BONDS_SEC_STRUCT_COLOUR=6,
      BONDS_NO_HYDROGENS=15,
      CA_BONDS_PLUS_LIGANDS_SEC_STRUCT_COLOUR=7,
      CA_BONDS_PLUS_LIGANDS_B_FACTOR_COLOUR=14,
      CA_BONDS_PLUS_LIGANDS_AND_SIDECHAINS=17,
      COLOUR_BY_MOLECULE_BONDS=8,
      COLOUR_BY_RAINBOW_BONDS=9,
      COLOUR_BY_B_FACTOR_BONDS=10,
      COLOUR_BY_OCCUPANCY_BONDS=11,
      COLOUR_BY_USER_DEFINED_COLOURS____BONDS=12,
      COLOUR_BY_USER_DEFINED_COLOURS_CA_BONDS=13,
      COLOUR_BY_CHAIN_GOODSELL=21 // 20230826-PE from coords/Bond_lines.h
   };
}

#endif // API_BOND_COLOUR_HH
