
#ifndef COOT_DOCSTRING_EXTRACT_HH
#define COOT_DOCSTRING_EXTRACT_HH

#include <string>
#include <unordered_map>

namespace coot {

   // Parse the doxygen-generated XML for molecules_container_t and return a
   // map of function-name -> python docstring. Returns an empty map if the
   // file cannot be read.
   //
   // This is used both at build time (to generate the embedded docstrings, see
   // make-docstrings-source.cc) and as a runtime fallback when the embedded
   // table is empty.
   std::unordered_map<std::string, std::string>
   parse_docstrings_from_doxygen_xml(const std::string &xml_file_name);

   // Return the docstrings that were embedded into the binary at build time
   // (generated by coot-make-docstrings into coot-docstrings-generated.cc).
   // This needs neither the source tree nor the doxygen XML at runtime.
   const std::unordered_map<std::string, std::string> &builtin_docstrings();

}

#endif // COOT_DOCSTRING_EXTRACT_HH
