
// Build-time tool: read the doxygen-generated XML for molecules_container_t
// and emit a C++ source file that embeds the docstrings into the binary, so
// that the API documentation is available at runtime without the source tree
// (or the doxygen XML) being present.
//
// Usage: coot-make-docstrings <input-xml> <output-cc>
//
// If the input XML does not exist or cannot be parsed, an output file with an
// empty docstring table is still written, so the build does not break.

#include <fstream>
#include <iostream>
#include <map>

#include "coot-docstring-extract.hh"

// C++ string-literal escaping so the generated file compiles regardless of
// what characters the docstrings contain (quotes, backslashes, newlines, ...).
static std::string escape_for_cxx(const std::string &s) {
   std::string out;
   out.reserve(s.size() + 16);
   for (char c : s) {
      switch (c) {
         case '\\': out += "\\\\"; break;
         case '"':  out += "\\\""; break;
         case '\n': out += "\\n";  break;
         case '\r': out += "\\r";  break;
         case '\t': out += "\\t";  break;
         default:   out += c;      break;
      }
   }
   return out;
}

int main(int argc, char **argv) {

   if (argc < 3) {
      std::cerr << "Usage: " << argv[0] << " <input-xml> <output-cc>" << std::endl;
      return 1;
   }

   std::string xml_file_name = argv[1];
   std::string out_file_name = argv[2];

   std::unordered_map<std::string, std::string> docstrings =
      coot::parse_docstrings_from_doxygen_xml(xml_file_name);

   // sort for stable, reproducible output
   std::map<std::string, std::string> sorted(docstrings.begin(), docstrings.end());

   std::ofstream f(out_file_name);
   if (!f) {
      std::cerr << "ERROR:: cannot open output file " << out_file_name << std::endl;
      return 1;
   }

   f << "// Generated by coot-make-docstrings - do not edit.\n";
   f << "// Source: " << xml_file_name << "\n";
   f << "\n";
   f << "#include \"coot-docstring-extract.hh\"\n";
   f << "\n";
   f << "const std::unordered_map<std::string, std::string> &\n";
   f << "coot::builtin_docstrings() {\n";
   f << "   static const std::unordered_map<std::string, std::string> m = {\n";
   for (const auto &p : sorted) {
      f << "      {\"" << escape_for_cxx(p.first) << "\", \""
        << escape_for_cxx(p.second) << "\"},\n";
   }
   f << "   };\n";
   f << "   return m;\n";
   f << "}\n";

   std::cout << "coot-make-docstrings: wrote " << sorted.size()
             << " docstrings to " << out_file_name << std::endl;

   return 0;
}
